### ISSUE TITLE
Access denied errors running PortableExecutable tests

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#10943]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/windows_nt_debug_prtest/3539/
```
System.Reflection.PortableExecutable.Tests.DebugDirectoryTests.CodeView_Loaded [FAIL]  
        System.UnauthorizedAccessException : Access to the path 'C:\Users\dotnet-bot\AppData\Local\Temp\tmp7490.tmp' is denied.
        Stack Trace:
              at System.IO.Win32FileSystem.DeleteFile(String fullPath)
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.Reflection.Metadata\tests\TestUtilities\LoaderUtilities.cs(36,0): at System.Reflection.Metadata.Tests.LoaderUtilities.LoadPEAndValidate(Byte[] peImage, Action`1 validator, Boolean useStream)
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.Reflection.Metadata\tests\PortableExecutable\DebugDirectoryTests.cs(39,0): at System.Reflection.PortableExecutable.Tests.DebugDirectoryTests.CodeView_Loaded()
     System.Reflection.PortableExecutable.Tests.PEReaderTests.GetSectionData_Loaded [FAIL]
        System.UnauthorizedAccessException : Access to the path 'C:\Users\dotnet-bot\AppData\Local\Temp\tmp7491.tmp' is denied.
        Stack Trace:
              at System.IO.Win32FileSystem.DeleteFile(String fullPath)
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.Reflection.Metadata\tests\TestUtilities\LoaderUtilities.cs(36,0): at System.Reflection.Metadata.Tests.LoaderUtilities.LoadPEAndValidate(Byte[] peImage, Action`1 validator, Boolean useStream)
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.Reflection.Metadata\tests\PortableExecutable\PEReaderTests.cs(239,0): at System.Reflection.PortableExecutable.Tests.PEReaderTests.GetSectionData_Loaded()
```

**Comment by tmat** [comment]
Seems like Interop.mincore.FreeLibrary(handle) doesn't sometimes immediately release unlock the file :(
So what should we do here? We can ignore the failure to delete the file and just leave it behind, but that would leave garbage leaving behind.

**Comment by stephentoub** [comment]
For completeness, just recording that they failed again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/windows_nt_debug_prtest/3570/consoleText

**Comment by stephentoub** [comment]
> Seems like Interop.mincore.FreeLibrary(handle) doesn't sometimes immediately release unlock the file

Is this a bug in FreeLibrary?

Is there something we're doing that's somehow keeping a ref count to it and preventing it from being freed deterministically, or something like that?

**Comment by stephentoub** [comment]
Again, here, but in a different test:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/dev_api/job/windows_nt_debug_prtest/430/consoleText
```
System.Reflection.PortableExecutable.Tests.PEReaderTests.GetMethodBody_Loaded [FAIL]
        System.UnauthorizedAccessException : Access to the path 'C:\Users\dotnet-bot\AppData\Local\Temp\tmp123A.tmp' is denied.
        Stack Trace:
  Discovered:  System.Resources.Reader.Tests
              at System.IO.Win32FileSystem.DeleteFile(String fullPath)
  Starting:    System.Resources.Reader.Tests
           D:\j\workspace\windows_nt_de---0cbbd14c\src\System.Reflection.Metadata\tests\TestUtilities\LoaderUtilities.cs(33,0): at System.Reflection.Metadata.Tests.LoaderUtilities.LoadPEAndValidate(Byte[] peImage, Action`1 validator)
           D:\j\workspace\windows_nt_de---0cbbd14c\src\System.Reflection.Metadata\tests\PortableExecutable\PEReaderTests.cs(213,0): at System.Reflection.PortableExecutable.Tests.PEReaderTests.GetMethodBody_Loaded()
```

**Comment by tmat** [comment]
Fixed by https://github.com/dotnet/corefx/pull/10945

**Comment by stephentoub** [comment]
@weshaggard, @joperezr, when do we plan to next merge from master to dev/api?  This issue is still taking out a fair number of legs in CI in dev/api; there's a fix in master.

**Comment by joperezr** [comment]
We don't have a defined time of how often we do these merges, it's more of a 'merge if we depend on a change from master' kind of thing. That said, I think we've been merging probably around once a week or two.

**Comment by joperezr** [comment]
Actually, I also need a merge because I want to integrate the packaging version work that @ericstj added in master, so I'll probably start that tomorrow.
