### ISSUE TITLE
CloneTxTests.Run failed in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#11995]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/centos7.1_release_prtest/521/consoleText

```
     System.Transactions.Tests.CloneTxTests.Run(cloneType: Normal, isoLevel: Serializable, forcePromote: False, completeClone: False, expectedStatus: Committed) [FAIL]
        Assert.Equal() Failure
        Expected: Committed
        Actual:   Aborted
        Stack Trace:
              at System.Transactions.Tests.CloneTxTests.Run(CloneType cloneType, IsolationLevel isoLevel, Boolean forcePromote, Boolean completeClone, TransactionStatus expectedStatus)
```

**Comment by stephentoub** [comment]
Failed again here:
https://ci.dot.net/job/dotnet_corefx/job/master/job/centos7.1_debug_prtest/1362/

**Comment by jimcarley** [comment]
Stephen,

Unfortunately there is not much information in the output to help figure out why the transaction is aborting. I am guessing it is a timeout for some reason, but I am not 100% sure.

Is there a way to add tracing to tests running inside xunit? Where does the output of such tracing get written to?

Thanks.

Jim

**Comment by jimcarley** [comment]
Also, for failed build/test runs, where can I find the testResults.xml file for the System.Transactions.Tests run for that build?

Jim

From: Jim Carley
Sent: Monday, October 10, 2016 1:31 PM
To: 'dotnet/corefx' <reply@reply.github.com>
Subject: RE: [dotnet/corefx] CloneTxTests.Run failed in CI (#11995)

Stephen,

Unfortunately there is not much information in the output to help figure out why the transaction is aborting. I am guessing it is a timeout for some reason, but I am not 100% sure.

Is there a way to add tracing to tests running inside xunit? Where does the output of such tracing get written to?

Thanks.

Jim

**Comment by jimcarley** [comment]
Never mind on my question about where to find the testResults.xml. I figured out how to find what I needed.

But I still have the question about tracing/logging from an xunit test.

Jim

From: Jim Carley
Sent: Monday, October 10, 2016 2:37 PM
To: 'dotnet/corefx' <reply@reply.github.com>
Subject: RE: [dotnet/corefx] CloneTxTests.Run failed in CI (#11995)

Also, for failed build/test runs, where can I find the testResults.xml file for the System.Transactions.Tests run for that build?

Jim

From: Jim Carley
Sent: Monday, October 10, 2016 1:31 PM
To: 'dotnet/corefx' <reply@reply.github.com>
Subject: RE: [dotnet/corefx] CloneTxTests.Run failed in CI (#11995)

Stephen,

Unfortunately there is not much information in the output to help figure out why the transaction is aborting. I am guessing it is a timeout for some reason, but I am not 100% sure.

Is there a way to add tracing to tests running inside xunit? Where does the output of such tracing get written to?

Thanks.

Jim

**Comment by stephentoub** [comment]
Failed again here:
https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_debug_prtest/1802/consoleText
```
System.Transactions.Tests.CloneTxTests.Run(cloneType: BlockingDependent, isoLevel: Snapshot, forcePromote: False, completeClone: False, expectedStatus: Aborted) [FAIL]
        System.Transactions.TransactionAbortedException : The transaction has aborted.
        ---- System.TimeoutException : Transaction Timeout
        Stack Trace:
              at System.Transactions.TransactionStateAborted.CreateBlockingClone(InternalTransaction tx)
              at System.Transactions.DependentTransaction..ctor(IsolationLevel isoLevel, InternalTransaction internalTransaction, Boolean blocking)
              at System.Transactions.Transaction.DependentClone(DependentCloneOption cloneOption)
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.Transactions\tests\CloneTxTests.cs(96,0): at System.Transactions.Tests.CloneTxTests.Run(CloneType cloneType, IsolationLevel isoLevel, Boolean forcePromote, Boolean completeClone, TransactionStatus expectedStatus)
```

**Comment by jimcarley** [comment]
Something weird is definitely going on with transaction timeouts. I have now seen failures where a transaction doesn’t timeout when expected and others where it times out too early. And the failures are all intermittent.

**Comment by jimcarley** [comment]
It looks like commit:
https://github.com/dotnet/corefx/commit/60e727a897891d3820ff7017806dbf807676a81d

fixed this issue. Closing.

**Comment by mellinoe** [comment]
I just hit this failure, but on Desktop. See https://github.com/dotnet/corefx/issues/23760. Is the issue still present on desktop and the test needs to be disabled or something?
