### ISSUE TITLE
Expect: 100-Continue header auto-added on HttpClient request on Linux

### ISSUE THREAD

**Issue by lukeamcmurray** [dotnet/corefx#11991]
Hi, we have an issue whereby an 'Expect: 100-Continue' header is being automatically added to all HttpClient POST/PUT requests when our .NET Core web api service is deployed to a linux environment (specifically Ubuntu 14.04/16.04). The header is not added when the service is run in a windows environment, both from within Visual Studio and directly in the console using dotnet run. 

Logging of the headers of the HttpClient in the service prior to calling SendAsync shows that the Expect header is not set, however logging of the HTTP requests on the server using tcpdump show that it is being set.

I have tried to remove the headers via, client.DefaultRequestHeaders.ExpectContinue = false; and client.DefaultRequestHeaders.Expect.Clear(); however they are still added.

Our issue is that our service must pass through a squid proxy whose version does not support the Expect header. We do not have control over this proxy and it's unlikely we will be able to update the version in the near future.

Cheers,
Luke

**Comment by davidsh** [comment]
cc: @stephentoub

**Comment by stephentoub** [comment]
@lukeamcmurray, I assume you're using the 1.0 release, correct?  Are you able to try newer bits?  This should already be fixed for the 1.1 release:
https://github.com/dotnet/corefx/blob/release/1.1.0/src/System.Net.Http/src/System/Net/Http/Unix/CurlHandler.EasyRequest.cs#L624-L630

**Comment by lukeamcmurray** [comment]
@stephentoub, are you referring to the version of System.Net.Http? In our project.json we are referencing package version 4.1.0 which I assume resolves to version 1.0.0 - I'm unsure how i can try version 1.1?

**Comment by lukeamcmurray** [comment]
@stephentoub, are you referring to the dotnet core version? I'm not entirely sure how the corefx version fits in or how I can use 1.1?

**Comment by stephentoub** [comment]
> are you referring to the dotnet core version

Yes, I was.  1.1 is due out in the relatively near future.  If you want to try it out before then, you can use the preview packages from https://dotnet.myget.org/feed/dotnet-core.  I'm hopeful you'll find your issues has been addressed.

**Comment by Priya91** [comment]
@lukeamcmurray .NET Core 1.1 is released now, you can get the bits from [here](https://www.microsoft.com/net/download/core#/current). Did upgrading the .NET Core version fix the bug?

**Comment by lukeamcmurray** [comment]
@Priya91 looks like it has been resolved in .NET Core 1.1.

**Comment by jimkubatai** [comment]
In net core 2.0 project still not work. What's problem? I tried to use System.Net.ServicePointManager.Expect100Continue = false, but it does not work. How to solve this problem with .net core?

On Windows all is ok, but when i run application on CentOS 7 i had exception: 

>  System.Net.WebException: The remote server returned an error: (417) Expectation failed.
   at System.Net.HttpWebRequest.GetResponse()
Code: 

```
        private StringBuilder CreateRequestPOST(string serializedData)
        {
            Encoding encoding = new UTF8Encoding();
            StringBuilder output = new StringBuilder();

            HttpWebRequest request = WebRequest.CreateHttp(_uri);

            request.Method = WebRequestMethods.Http.Post;
            request.Credentials = CredentialCache.DefaultCredentials;
            request.Accept = "application/json";
            request.ContentType = "application/json";
            request.ContentLength = encoding.GetByteCount(serializedData);

            using (Stream requestStream = request.GetRequestStream())
            {
                requestStream.Write(encoding.GetBytes(serializedData), 0,
                    encoding.GetByteCount(serializedData));
            }

            Console.WriteLine(request.Headers);
            WebResponse response = request.GetResponse();

            lock (locker)
            {
                Requests++;
            }

            using (StreamReader reader = new StreamReader(response.GetResponseStream()))
            {
                output.Append(reader.ReadToEnd());
                response.Close();
            }

            return output;
        }
```
