### ISSUE TITLE
[ARM/CI] Add arm-hardfp checks to CI

### ISSUE THREAD

**Issue by wateret** [dotnet/corefx#12545]
`Linux ARM Emulator Cross` is actually arm-softfp. I think we also need one for arm-hardfp.

There is a work for this in CoreCLR too. https://github.com/dotnet/coreclr/issues/7412

/cc @sjsinju

**Comment by wateret** [comment]
Before making changes I need to put up the rootfs image for arm-hardfp to CI server.
I am going to use [rootfs-u1404.20160607.ext4](https://dncorerepo.blob.core.windows.net/armemulator/rootfs-u1404.20160607.ext4.tar.pbz2) which is specified in https://github.com/dotnet/coreclr/issues/3805.

/cc @jashook

**Comment by wateret** [comment]
@dotnet-bot help

**Comment by mellinoe** [comment]
@wateret Has this issue been addressed by #13543?

**Comment by mellinoe** [comment]
Hey @wateret , is there more to be done for this issue?

**Comment by wateret** [comment]
@mellinoe Yes. [LinuxARMEmulator HardFP](https://ci.dot.net/job/dotnet_corefx/job/master/job/linuxarmemulator_hardfp_cross_debug/) still fails. Probably there will be no more PRs for the issue, some work must be done on the CI machine. The work is in progress with @jashook.
