### ISSUE TITLE
Added additional WellKnownSidType enumeration members

### ISSUE THREAD

**Issue by karelz** [dotnet/corefx#14636]
We need to decide on https://github.com/dotnet/corefx/pull/14611#discussion_r93085854

Looks like the thing which uses [`MaxDefined`](https://github.com/dotnet/corefx/blob/master/src/System.Security.Principal.Windows/src/System/Security/Principal/SID.cs#L114) in a validator is the product code.  https://referencesource.microsoft.com/#mscorlib/system/security/principal/sid.cs,491, and without updating it (in the impl) it'll make the new values unusable.

Options:
1.  Take the breaking change of updating it
2. Take the breaking change of undefining it
3. Update it in the impl, but not the ref
4. Say we're never allowed to update this enumeration
5. Leave this value as-is, but change the product code to do something smarter.
6. Some other proposal.

cc @couven92 @bartonjs @terrajobst @weshaggard, @ericstj

**Comment by terrajobst** [comment]
I think we should do (5).

**Comment by karelz** [comment]
I can handle the docs once we finish & merge the changes.
@couven92 do you want to finish your change with the feedback above?

**Comment by couven92** [comment]
Done in commit c838dc7

I could also add an `[Obosolete]` attribute on the `MaxDefined` member if you want...

**Comment by karelz** [comment]
Yes please: https://github.com/dotnet/corefx/pull/14611#discussion_r93529681

**Comment by danmosemsft** [comment]
@couven92 do you want to do that bit so we can close this?

**Comment by couven92** [comment]
@danmosemsft I think the update of the WellKnownSidType enumeration in `src/System.Security.Principal.Windows/src/System/Security/Principal/SID.cs` is done, I added the new Enum values, we left MaxDefined where it was before and added Obsolete and EditorBrowsable attributes to discourage people from using that value
Thanks to @karelz I also follwed all nit-picking comment on the code, so unless I missed something, that part is good to go after commit 4d30256

Initially there was some talk that the reference source in https://github.com/dotnet/corefx/blob/master/src/System.Security.Principal.Windows/ref/System.Security.Principal.Windows.cs and also on https://referencesource.microsoft.com/#mscorlib/system/security/principal/sid.cs,491 needed to be updated for this. Should I copy my changes to the reference source file?

I also agree on @bartonjs comment in #14611 saying that we should have some tests for the new values. I'd think that the best way to test this is to see if these values can be used to create valid Windows Indentifier instances. I could write these tests if you want me to?

**Comment by danmosemsft** [comment]
Sure, tests would be welcome.

Yes, the additions aren't useable without matching updates to the file in ref. They will need to be wrapped in `#if netcoreapp11`. However I see a comment here https://github.com/dotnet/corefx/pull/14611#pullrequestreview-13607431 that that may be an issue. I pinged folks on that comment to give a verdict.

https://referencesource.microsoft.com matches Desktop - we do not update it ourselves. (https://source.dot.net incidentally is the .NET Core index)

**Comment by ViktorHofer** [comment]
@couven92 any progress on the tests?

**Comment by couven92** [comment]
@ViktorHofer https://github.com/dotnet/corefx/pull/14611 includes the test and has been merged.

**Comment by ViktorHofer** [comment]
Closing this as all concerns are addressed.

**Comment by weshaggard** [comment]
We do still have some test failures to address but that is issue https://github.com/dotnet/corefx/issues/15436.
