### ISSUE TITLE
NullReferenceException in FileSystemWatcher in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#1556]
```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
     at System.IO.FileSystemWatcher.get_IsHandleInvalid()
     at System.IO.FileSystemWatcher.Monitor(Byte[] buffer)
     at System.IO.FileSystemWatcher.CompletionStatusChanged(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* overlappedPointer)
     at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)

d:\j\workspace\dotnet_corefx_windows_debug_prtest\packages\Microsoft.DotNet.BuildTools.1.0.25-prerelease-00040\lib\tests.targets(101,5): warning MSB3073: The command "corerun.exe xunit.console.netcore.exe System.IO.FileSystem.Watcher.Tests.dll  -xml testResults.xml -notrait category=nonwindowstests  -notrait category=OuterLoop -notrait category=failing " exited with code -1073741819. [d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.IO.FileSystem.Watcher\tests\System.IO.FileSystem.Watcher.Tests.csproj]
d:\j\workspace\dotnet_corefx_windows_debug_prtest\packages\Microsoft.DotNet.BuildTools.1.0.25-prerelease-00040\lib\tests.targets(112,5): error : One or more tests failed while running tests from 'System.IO.FileSystem.Watcher.Tests' please check log for details! [d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.IO.FileSystem.Watcher\tests\System.IO.FileSystem.Watcher.Tests.csproj]
```
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_debug_prtest/1052/console

**Comment by krwq** [comment]
cc: @sokket

**Comment by chcosta** [comment]
@stephentoub, have you happened to notice this occurring frequently or is this an infrequent occurrence?

@ericstj, in FileSystemWatcher.Win32.cs

56         private void StopRaisingEvents() 
57         { 
58             // If we're not attached, do nothing. 
59             if (IsHandleInvalid) 
60             { 
61                 return; 
62             } 
63 
64             // Close directory handle 
65             // This operation doesn't need to be atomic because the API will deal with a closed 
66             // handle appropriately. 
67             // Ensure that the directoryHandle is set to INVALID_HANDLE before closing it, so that 
68             // the Monitor() can shutdown appropriately. 
69             // If we get here while asynchronously waiting on a change notification, closing the 
70             // directory handle should cause CompletionStatusChanged be be called 
71             // thus freeing the pinned buffer. 
72             _stopListening = true; 
73             _directoryHandle.Dispose(); 
74             _directoryHandle = null; 
75 
76             // Start ignoring all events occurring after this. 
77             Interlocked.Increment(ref _currentSession); 

Is setting _directoryHandle to null during "StopRaisingEvents" required?  I'm trying to track down why we would get a NullReferenceException during an "IsHandleInvalid" check, and it seems possible that we could call StopRaisingEvents right when we get a CompletionStatusChanged event.  The code looks like it gracefully ensures directoryHandle is set to INVALID_HANDLE before closing it, but then sets it to null. The window where this would lead to an exception is extremely small though since we do a null check as part of the "IsHandleInvalid" properties getter.  An alternative is to create a local SafeFileHandle for comparison to avoid the chance of the NullRefException.

It would be nice to know which test this failed in, and a repro but I find it unlikely that either of those two things will occur.  If this has been seen multiple times, that's probably a good data point since the above scenario is very unlikely and I'd be curious to know what changed recently to cause this.

**Comment by stephentoub** [comment]
> have you happened to notice this occurring frequently or is this an infrequent occurrence?

I only hit it this once.

**Comment by chcosta** [comment]
I was able to repro this by creating a unit test which creates two threads.

Thread 1: Create and delete a file
Thread 2: Enable and disable raising events

I then ran thread 1 and thread 2 using the same FileSystemWatcher for 30 seconds.  On average, it took less than 10 seconds for a NullReferenceException to fire.  

I have a local fix for this, which is to remove the "_directoryHandle=null" statement.  Not setting _directoryHandle to null means the GC won't collect it.  Whenever we start raising events, we initialize "_directoryHandle" to refer to the directory being monitored.  An alternative solution would be to use a lock, but that is a bit heavy handed and not necessary unless we believe setting _directoryHandle to null is a requirement.

I'll create a PR for the change and reference this issue as context.

Given that this is for a race condition, the unit test is not gauranteed to catch an instance / regression in this area, so I won't include the unit test with my PR.

**Comment by stephentoub** [comment]
Fixed by #1649

**Comment by NickRedwood** [comment]
@chcosta - hopefully this is an ok place to ask, would you mind posting the code that reproduces this issue? The problem still exists in .NET Framework and I would like to test against it. Thanks.

**Comment by chcosta** [comment]
@NickRedwood , sadly, I don't have the code still laying around.

**Comment by NickRedwood** [comment]
@chcosta - never mind, thanks anyway.
