### ISSUE TITLE
Use SetThreadErrorMode instead of SetErrorMode

### ISSUE THREAD

**Issue by jkotas** [dotnet/corefx#19738]
SetErrorMode Windows API is process global and thus it suffers from race condition when multiple threads are flipping the error mode back and forth.

File I/O on Windows should be using SetThreadErrorMode instead (this API is supported on Win7+).

The full framework calls SetThreadErrorMode on Win7+: https://github.com/Microsoft/referencesource/blob/4fe4349175f4c5091d972a7e56ea12012f1e7170/mscorlib/microsoft/win32/win32native.cs#L1480. Calling SetThreadErrorMode instead of SetErrorMode will both  fix the race condition and improve compatibility with full framework.

**Comment by jkotas** [comment]
(This needs to be fixed in both coreclr and corefx.)

**Comment by danmosemsft** [comment]
Reached out to ask for it in WACK

**Comment by karelz** [comment]
Feels like 2.0 blocker ... due to reliability angle.

**Comment by JeremyKuhne** [comment]
I'll fix it on Monday.

**Comment by JeremyKuhne** [comment]
@zamont Is changing this for System.Private.Corelib in ProjectN- I assume the shared folder will sync to CoreCLR?

**Comment by jkotas** [comment]
You should fix this in CoreCLR and let it propagate to CoreRT/ProjectN from there.

**Comment by zamont** [comment]
I can hold off on checking in my ProjectN change until the change in CoreCLR propagates to CoreRT/ProjectN (my changes depend on SetThreadErrorMode existing)

**Comment by jkotas** [comment]
@zamont Yes, it would be useful - it will avoid the conflicts. There is number of extra changes needed in CoreCLR in addition to what your delta has.

**Comment by JeremyKuhne** [comment]
I'll update System.Private.Corelib here then (as a start). It doesn't look like the native bits are shared?

**Comment by danmosemsft** [comment]
CoreRT and CoreCLR do not share native bits via the auto syncer. @jkotas is there any native sharing likely to happen someday?

**Comment by jkotas** [comment]
We do share some native bits, like GC (via manual process - it may be nice to turn on the auto syncer for it when we get a chance).

The assembly loader which contains the SetErrorMode calls are in CoreCLR is unlikely to be ever shared. It has been rewritten in C# for CoreRT.

**Comment by danmosemsft** [comment]
This is not going to go through shiproom.

**Comment by karelz** [comment]
@danmosemsft why not? This is reliability and compat problem.

**Comment by danmosemsft** [comment]
Because as far as I'm aware the code has been this way forever and I haven't seen recent issues root caused to this. Moved it back though, I don't feel strongly either way.

**Comment by karelz** [comment]
Oh, I didn't understand it that way - maybe I am wrong.
@jkotas can you please comment on the impact on reliability? Is it new .NET Core? Or is it same as in .NET Framework?

**Comment by jkotas** [comment]
#19801 and https://github.com/dotnet/coreclr/issues/11625 make us bug for bug compatible with desktop. Both these PRs are in release/2.0.0

However the behavior in desktop is not quite right and inconsistent (https://github.com/dotnet/corefx/pull/19801#discussion_r116656403). It will open a new post 2.0 issue about that.

**Comment by karelz** [comment]
Hmmm, not sure if I follow. Was this particular issue fixed in 2.0 yet? Or not? (want to fix the milestone)

**Comment by stephentoub** [comment]
@karelz, yes, you can see the PR that fixed it here: https://github.com/dotnet/corefx/pull/19801 (it's linked above).  There are multiple ways for you to check whether this is in the 2.0 branch, but a quick-and-easy way: just search the list of commits in the merge PR here: https://github.com/dotnet/corefx/pull/19891.

**Comment by JeremyKuhne** [comment]
Fyi: I did finally confirm that the prompting behavior still exists. The detail I was missing is that the file systems for removable media don't load until you actually use media in them. So if you have a floppy or cd drive you won't get the prompt if you haven't put a disk in since booting. You'll get the same prompt for a USB floppy or built-in, but, again, you have to have used a floppy since booting to get the prompt.

**Comment by karelz** [comment]
Thanks for confirmation @stephentoub! It wasn't clear to me which PR actually fixed the problem vs. not.

**Comment by jkotas** [comment]
#19921 tracks the post 2.0 follow up.
