### ISSUE TITLE
ILC optimization causes reflection to fail in System.Net.Primitives CookieParser

### ISSUE THREAD

**Issue by joperezr** [dotnet/corefx#20482]
test `SetCookies_InvalidData_Throws` is throwing a Debug.Assert in Debug uapaot ilc test runs, so the test will be disabled in order for the test run to complete. This issue is to track the work of fixing the issue causing the Debug.Assert to be called, and for re-enabling the test.

**Comment by danmosemsft** [comment]
can you include the assert / stack if available ?

**Comment by joperezr** [comment]
Sure, do keep in mind that it is an ilc executable which means that callstack might not be super helpful but I'm able to debug using VS so I can help to get a repro if required. Relevant part of the callstack is:
```
xunit.console.netcore.dll!System::Diagnostics::Debug.ShowAssertDialog(System::String & message, System::String & detailMessage={...}, System::String &) Line 22
xunit.console.netcore.dll!System::Threading::IOCompletionCallback.InvokeOpenStaticThunk(unsigned int errorCode, unsigned int numBytes=24087316, System::Threading::NativeOverlapped * pOVERLAP=0x016bd7b8)
xunit.console.netcore.dll!$3_Newtonsoft::Json::Serialization::ExtensionDataSetter.Invoke(System::Object & o, System::String & key={...}, System::Object & value={...})
xunit.console.netcore.dll!System::Diagnostics::Debug.Assert(bool condition, System::String & message={...}, System::String & detailMessage={...}) Line 107
xunit.console.netcore.dll!$26_System::Net::CookieParser.Get() Line 622
xunit.console.netcore.dll!$26_System::Net::CookieContainer.CookieCutter($44_System::Uri & uri={...}, System::String & headerName, System::String & setCookieHeader={...}, bool isThrow=true) Line 669
xunit.console.netcore.dll!$25_System::Net::Primitives::Functional::Tests::CookieContainerTest::<>c__DisplayClass29_0.<SetCookies_InvalidData_Throws>b__0() Line 157
```

**Comment by joperezr** [comment]
just to add more info, the Assert we are hitting seems to be this one: https://github.com/dotnet/corefx/blob/master/src/Common/src/System/Net/CookieParser.cs#L558

**Comment by hughbe** [comment]
This is because we moved `CookieParser` to common and use reflection to access internal methods in order to fix an HttpListener porting bug.

From the file: https://github.com/dotnet/corefx/blob/9b6844c1c61a4da6b46d111cd9e92004c5c4f9bf/src/Common/src/System/Net/CookieParser.cs#L547

```
        private static Func<Cookie, string, bool> s_internalSetNameMethod;
        private static Func<Cookie, string, bool> InternalSetNameMethod
        {
            get
            {
                if (s_internalSetNameMethod == null)
                {
                    // We need to use Cookie.InternalSetName instead of the Cookie.set_Name wrapped in a try catch block, as
                    // Cookie.set_Name keeps the original name if the string is empty or null.
                    // Unfortunately this API is internal so we use reflection to access it. The method is cached for performance reasons.
                    MethodInfo method = typeof(Cookie).GetMethod("InternalSetName", BindingFlags.NonPublic | BindingFlags.Instance);
                    Debug.Assert(method != null, "We need to use an internal method named InternalSetName that is declared on Cookie.");
                    s_internalSetNameMethod = (Func<Cookie, string, bool>)Delegate.CreateDelegate(typeof(Func<Cookie, string, bool>), method);
                }

                return s_internalSetNameMethod;
            }
        }
```

**Comment by tijoytom** [comment]
Should be fixed by #21280

**Comment by tijoytom** [comment]
@joperezr This should be fixed now , but i can't find the PR to figure out the test that you disabled. Can you please re-enable them ?

**Comment by joperezr** [comment]
@tijoytom I tried running this locally and test is not fixed yet.

**Comment by tijoytom** [comment]
What's the call stack like ?

**Comment by CIPop** [comment]
/cc @yizhang82 

The stack looks wrong (line-number doesn't match with a Debug statement. 
This could be due to some optimizations or because my source code is out of sync with the binary. Currently rebuilding everything and will give it another try.

```

        private static Func<Cookie, string, bool> InternalSetNameMethod
        {
            get
            {
                if (s_internalSetNameMethod == null)
                {
                    // We need to use Cookie.InternalSetName instead of the Cookie.set_Name wrapped in a try catch block, as
                    // Cookie.set_Name keeps the original name if the string is empty or null.
                    // Unfortunately this API is internal so we use reflection to access it. The method is cached for performance reasons.
                    BindingFlags flags = BindingFlags.Instance;
#if uap
                    flags |= BindingFlags.Public;   <------------------------- stack shows that the assert is thrown after this line in my case which seems wrong.
#else
                    flags |= BindingFlags.NonPublic;
#endif
                    MethodInfo method = typeof(Cookie).GetMethod("InternalSetName", flags);
                    Debug.Assert(method != null, "We need to use an internal method named InternalSetName that is declared on Cookie.");
                    s_internalSetNameMethod = (Func<Cookie, string, bool>)Delegate.CreateDelegate(typeof(Func<Cookie, string, bool>), method);
                }

```

```
 # Child-SP          RetAddr           Call Site
00 00000074`f48fc340 00007ffa`093ed62c KERNELBASE!RaiseFailFastException+0xae [minkernel\kernelbase\xcpt.c @ 1106] 
01 (Inline Function) --------`-------- xunit_console_netcore!$75___Interop::kernel32_dll::PInvoke_RaiseFailFastException+0x43 [C:\Users\crispop\AppData\Local\Temp\Ilc241060349\xunit.console.netcore.McgInterop\PInvoke.g.cs @ 1060] 
02 00000074`f48fc910 00007ffa`091bcd2e xunit_console_netcore!System::Diagnostics::Debug.ShowAssertDialog+0xbc [f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\Diagnostics\Debug.Windows.cs @ 22] 
03 00000074`f48fca80 00007ffa`091bce34 xunit_console_netcore!System::Action$3<System::__Canon,System::__Canon,System::__Canon>.InvokeOpenStaticThunk+0x2e [InvokeOpenStaticThunk @ 15732480] 
04 00000074`f48fcab0 00007ffa`092f5e1c xunit_console_netcore!System::Action$3<System::__Canon,System::__Canon,System::__Canon>.Invoke+0x34 [Invoke @ 15732480] 
05 00000074`f48fcaf0 00007ffa`094e06cb xunit_console_netcore!System::Diagnostics::Debug.Assert+0x6c [f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\shared\System\Diagnostics\Debug.cs @ 105] 
06 (Inline Function) --------`-------- xunit_console_netcore!System::Diagnostics::Debug::Assert+0x1b [f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\shared\System\Diagnostics\Debug.cs @ 84] 
07 00000074`f48fcb30 00007ffa`094e01d5 xunit_console_netcore!$25_System::Net::CookieParser.get_InternalSetNameMethod+0x8b [S:\corefxUwpAot\src\Common\src\System\Net\CookieParser.cs @ 559] 
08 00000074`f48fcb90 00007ffa`094dfd3f xunit_console_netcore!$25_System::Net::CookieParser.Get+0xb5 [S:\corefxUwpAot\src\Common\src\System\Net\CookieParser.cs @ 622] 
09 00000074`f48fcc40 00007ffa`094dfa7a xunit_console_netcore!$25_System::Net::CookieContainer.CookieCutter+0x29f [S:\corefxUwpAot\src\System.Net.Primitives\src\System\Net\CookieContainer.cs @ 671] 
0a (Inline Function) --------`-------- xunit_console_netcore!$25_System::Net::CookieContainer::SetCookies+0x12 [S:\corefxUwpAot\src\System.Net.Primitives\src\System\Net\CookieContainer.cs @ 985] 
0b 00000074`f48fcd10 00007ffa`094d0f82 xunit_console_netcore!$24_System::Net::Primitives::Functional::Tests::CookieContainerTest::<>c__DisplayClass29_0.<SetCookies_InvalidData_Throws>b__0+0x2a [S:\corefxUwpAot\src\System.Net.Primitives\tests\FunctionalTests\CookieContainerTest.cs @ 157] 
```

**Comment by davidsh** [comment]
@CIPop 

You can run tests using the ILCBuildType switch so that everything stays debug when the ILC.EXE runs:

>msbuild /t:rebuildandtest /p:TargetGroup=uapaot /p:Outerloop=true /p:ILCBuildType=chk

**Comment by CIPop** [comment]
This is very similar to #21233. 

@yizhang82 @tijoytom Since this is a problem only in UapAot (passes in Uap) it is definitely related to some optimization made by ILC. 
I remember that in the past we needed to give ILC some hits on what reflection types should be preserved but I don't remember how that's done. Could you help us with some hits/docs?

@davidsh's build command removed the optimization. It's the Debug assert which fails:
```
08 0000004f`154f9e50 00007ff8`b105f18a xunit_console_netcore!System::Diagnostics::Debug.Assert+0xb6 [f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\shared\System\Diagnostics\Debug.cs @ 107] 
09 0000004f`154f9eb0 00007ff8`b152a001 xunit_console_netcore!System::Diagnostics::Debug.Assert+0x4a [f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\shared\System\Diagnostics\Debug.cs @ 86] 
0a 0000004f`154f9ef0 00007ff8`b152942a xunit_console_netcore!$25_System::Net::CookieParser.get_InternalSetNameMethod+0x101 [S:\corefxUwpAot\src\Common\src\System\Net\CookieParser.cs @ 564] 
0b 0000004f`154f9f80 00007ff8`b1528b82 xunit_console_netcore!$25_System::Net::CookieParser.Get+0x1ca [S:\corefxUwpAot\src\Common\src\System\Net\CookieParser.cs @ 628] 
0c 0000004f`154fa220 00007ff8`b1528559 xunit_console_netcore!$25_System::Net::CookieContainer.CookieCutter+0x612 [S:\corefxUwpAot\src\System.Net.Primitives\src\System\Net\CookieContainer.cs @ 671] 
0d 0000004f`154fa4b0 00007ff8`b152c14b xunit_console_netcore!$25_System::Net::CookieContainer.SetCookies+0xf9 [S:\corefxUwpAot\src\System.Net.Primitives\src\System\Net\CookieContainer.cs @ 986] 
0e 0000004f`154fa510 00007ff8`b10a0524 xunit_console_netcore!$24_System::Net::Primitives::Functional::Tests::CookieContainerTest::<>c__DisplayClass29_0.<SetCookies_InvalidData_Throws>b__0+0x5b [S:\corefxUwpAot\src\System.Net.Primitives\tests\FunctionalTests\CookieContainerTest.cs @ 158] 
```

(Part of main scenario - marked as blocking release.)

**Comment by davidsh** [comment]
I have a theory about why this test is failing and why reflection isn't working despite marking the API as "public" in the implementation.

The file CookieParser.cs is a located here

and is used in both the System.Net.Primitives library as well as separately included as part of the System.Net.HttpListener (managed listener) code.  The reflection works when this file is included in the System.Net.HttpListener library; otherwise we would have seen UAPAOT failures in HttpListener.

But it seems that in the System.Net.Primitives library itself, the reflection doesn't work. And I think it doesn't work because it is trying to reflecton a (public) API that is in the same type from which the reflection call is made. So, perhaps the ILC compiler is thinking to strip out that reflection because it perceives it as un-necessary.  Why would reflection be used within the same type itself. It could simply call the method directly.

@tijoytom @yizhang82 Can you confirm my theory?

If this theory hold, then we need to special ifdef the code so that it doesn't use reflection is the source file is included in the System.Net.Primitives library itself vs. System.Net.HttpListener which needs to use the reflection.

**Comment by davidsh** [comment]
I was able to verify my theory and have submitted a PR #21584. If we're using the common file and including it directly in System.Net.Primitives, we don't need to use reflection anyways.

**Comment by CIPop** [comment]
This is crashing when running HttpListener tests:

```
 # Child-SP          RetAddr           Call Site
00 000000ad`51eff070 00007ffb`d37f20fc KERNELBASE!RaiseFailFastException+0x74 [minkernel\kernelbase\xcpt.c @ 1106] 
01 (Inline Function) --------`-------- xunit_console_netcore!$77___Interop::kernel32_dll::PInvoke_RaiseFailFastException+0x43 [PInvoke_RaiseFailFastException @ 16707565] 
02 000000ad`51eff640 00007ffb`d35cf26e xunit_console_netcore!System::Diagnostics::Debug.ShowAssertDialog+0xbc [f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\Diagnostics\Debug.Windows.cs @ 22] 
03 000000ad`51eff7b0 00007ffb`d35cf374 xunit_console_netcore!$4_Newtonsoft::Json::Serialization::ExtensionDataSetter.InvokeOpenStaticThunk+0x2e [InvokeOpenStaticThunk @ 15732480] 
04 000000ad`51eff7e0 00007ffb`d370484c xunit_console_netcore!System::Action$3<System::__Canon,System::__Canon,System::__Canon>.Invoke+0x34 [Invoke @ 15732480] 
05 000000ad`51eff820 00007ffb`d39be2db xunit_console_netcore!System::Diagnostics::Debug.Assert+0x6c [f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\shared\System\Diagnostics\Debug.cs @ 105] 
06 (Inline Function) --------`-------- xunit_console_netcore!System::Diagnostics::Debug::Assert+0x1b [f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\shared\System\Diagnostics\Debug.cs @ 84] 
07 000000ad`51eff860 00007ffb`d39bdfb7 xunit_console_netcore!$23_System::Net::CookieParser.get_InternalSetNameMethod+0x8b [R:\corefxUwpAot\src\Common\src\System\Net\CookieParser.cs @ 571] 
08 000000ad`51eff8c0 00007ffb`d39bde93 xunit_console_netcore!$23_System::Net::CookieParser.GetServer+0xa7 [R:\corefxUwpAot\src\Common\src\System\Net\CookieParser.cs @ 811] 
09 000000ad`51eff930 00007ffb`d39bdca2 xunit_console_netcore!$23_System::Net::HttpListenerRequest.ParseCookies+0x153 [R:\corefxUwpAot\src\System.Net.HttpListener\src\System\Net\HttpListenerRequest.cs @ 36] 
0a 000000ad`51eff990 00007ffb`d39d07fe xunit_console_netcore!$23_System::Net::HttpListenerRequest.get_Cookies+0x52 [R:\corefxUwpAot\src\System.Net.HttpListener\src\System\Net\HttpListenerRequest.cs @ 62] 
0b 000000ad`51eff9d0 00007ffb`d372c514 xunit_console_netcore!$24_System::Net::Tests::HttpListenerRequestTests::<Cookies_GetProperty_ReturnsExpected>d__38.MoveNext+0x11e [R:\corefxUwpAot\src\System.Net.HttpListener\tests\HttpListenerRequestTests.cs @ 597] 
0c 000000ad`51effa70 00007ffb`d370ca47 xunit_console_netcore!System::Runtime::CompilerServices::AsyncMethodBuilderCore::MoveNextRunner::<>c.<CallMoveNext>b__3_0+0x14 [f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\Runtime\CompilerServices\AsyncMethodBuilder.cs @ 849] 

```
