### ISSUE TITLE
BinarySearchSZArray tests failing in ILC

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/corefx#21379]
```
BinarySearch_SZArray<Int16>(array: [-32768, 0, 0, 32767], index: 0, length: 1, value: -32768, comparer: null, expected: 0)	
BinarySearch_SZArray<Int16>(array: [-32768, 0, 0, 32767], index: 0, length: 4, value: -32768, comparer: null, expected: 0)	
BinarySearch_SZArray<Int16>(array: [-32768, 0, 0, 32767], index: 1, length: 3, value: -32768, comparer: null, expected: -2)	
BinarySearch_SZArray<SByte>(array: [-128, 0, 0, 127], index: 0, length: 1, value: -128, comparer: null, expected: 0)	
BinarySearch_SZArray<SByte>(array: [-128, 0, 0, 127], index: 0, length: 4, value: -128, comparer: null, expected: 0)	
BinarySearch_SZArray<SByte>(array: [-128, 0, 0, 127], index: 1, length: 3, value: -128, comparer: null, expected: -2)	
IndexOf_SZArray<ArrayTests+Int16Enum>(array: [Min], value: Min, startIndex: 0, count: 1, expected: 0)
```

https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Filc~2F/build/20170622.02/workItem/System.Runtime.Tests.Execution
eg 
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Filc~2F/build/20170622.02/workItem/System.Runtime.Tests.Execution/analysis/xunit/System.Tests.ArrayTests~2FBinarySearch_SZArray%3CInt16%3E(array:%20%5B-32768,%200,%200,%2032767%5D,%20index:%200,%20length:%201,%20value:%20-32768,%20comparer:%20null,%20expected:%200)

@joshfree can you please assign to a dev on your side.

**Comment by joshfree** [comment]
@AtsushiKan can you please take the first look?

**Comment by AtsushiKan** [comment]
@fadimounir - this is another ARM failure and it has all the signs I've come to associate with USG problems. (the generic theory method, first failure on a non-system type, ...)

Please take a look.

**Comment by Jiayili1** [comment]
Failed again: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Filc~2F/build/20170630.01/workItem/System.Runtime.Tests.Execution

**Comment by danmosemsft** [comment]
@fadimounir is this on your radar?

**Comment by fadimounir** [comment]
Yes it is. I'm planning on looking into this issue this week.

**Comment by fadimounir** [comment]
Can anyone tell me how to repro this locally?

Here are instructions I got from Matt for a previous failure I needed to investigate:

> 1)	Get your access token from https://helix.dot.net/ (sign in in top right, go to your profile, copy GitHub key)
> 2)	Get the test name (in this case it’s System.Text.Encoding.Tests.Execution minus the “.Execution”)
> 3)	Get the Correlation ID from below link  (a2defa82-3539-4cdb-8b87-5e7b8e4a3512)
> 4)	Use the repro tool to rerun the test case, e.g.:
> 
> dotnet exec \\helixutil\tools\repro\HelixJobReproCore.dll --token <value from #1> --job a2defa82-3539-4cdb-8b87-5e7b8e4a3512 --workitem  System.Text.Encoding.Tests --repropath <Some path on your machine>
> 

Now what's the correlation ID for this failure?

**Comment by MattGal** [comment]
These multi-pass ARM tests are a bit special since the part you want to debug is not likely the result from the link above.  We'd like to merge things but we'd need to introduce some higher-level concept of test result grouping to do so.  That said, here's what you want:

Starting from @Jiayili1's link above, to get the correlation id I do the following:

1) Click link
2) Click "Infrastructure Execution logs"
3) Select flavor.  In this case, since we're debugging a thing, probably debug.  So, I click "Windows.10.Amd64-arm:Debug"
4) Here, I see that the job's correlation id was 7fd0cc0d-972b-4132-81bf-8cc414c52cd2

At this point the instructions you've already got should get the bits onto your machine in the path of your choice (specified by the --repropath arg).  If Python 2.7 isn't present and in the expected path, the tests won't run autoatically, but everything you need to run them will be on disk (you'll just need to CD into the directory with RunTests.cmd and call it with the path that will be now inside env var "%HELIX_CORRELATION_PAYLOAD%"

**Comment by fadimounir** [comment]
Thanks @MattGal

**Comment by fadimounir** [comment]
Fixed in the N branch.

**Comment by Jiayili1** [comment]
This issue is still repro, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Filc~2F/build/20170712.01/workItem/System.Runtime.Tests.Execution/analysis/xunit/System.Tests.ArrayTests~2FBinarySearch_SZArray%3CInt16%3E(array:%20%5B-32768,%200,%200,%2032767%5D,%20index:%200,%20length:%201,%20value:%20-32768,%20comparer:%20null,%20expected:%200)

**Comment by joperezr** [comment]
@fadimounir do you mind checking if your fix is already includded in the ILC we use in master?

**Comment by joperezr** [comment]
apparently making the ILCBuildType chk will have these tests pass so we could use that as a workaround.
```xml
<PropertyGroup>
   <ILCBuildType>chk</ILCBuildType>
</PropertyGroup>
```

**Comment by fadimounir** [comment]
This is a codegen bug with signed arithmetics. Looks like it's affecting SByte.CompareTo and Int16.CompareTo.

Here's a comparison between codegen for SByte.CompareTo with optimizations and without optimizations:

> 636008D8  nop  
636008DA  ldr         r3,[sp,#this]  
636008DC  ldrsb       r2,[r3]  						=> 00000000
636008E0  ldrsb       r3,[sp,#value]  					=> FFFFFF80
636008E4  sub         r3,r2,r3  					=> 00000080
636008E8  str         r3,[sp]  
636008EA  b           System::SByte.CompareTo+4Ch (636008ECh)  
636008EC  ldr         r3,[sp]  
636008EE  str         r3,[sp,#4]  
636008F0  ldr         r0,[sp,#4]  
636008F2  pop         {r2,r3,r11}  
636008F6  ldr         pc,[sp],#0xC  

And:

> 61CF04D8  push        {r11,lr}  
61CF04DC  mov         r11,sp  
61CF04DE  ldrsb       r3,[r0]  
61CF04E2  sub         r0,r3,r1  
61CF04E6  pop         {r11,pc}

**Comment by DGilliesMS** [comment]
Looks like it may be calling convention converter issue.  DavidWr is going to have a look.  Here are some details from an email (and skype) thread between DavidWr, Fadi and me:

So I believe that this what is expected:
Int8, int16 – sign extend to 32 bits.
Uint8, uint16 – zero extend to 32 bits.  I believe this includes Boolean representation (a uint8 essentially).
I don’t think 64 bits changes this but will see if I can find further information.

Dave
From: David Wrighton 
Sent: Friday, July 14, 2017 10:59 AM
To: Fadi Hanna <fadim@microsoft.com>; David Gillies <dgillies@microsoft.com>
Subject: RE: David Gillies sent you a message in Skype for Business-Fadi Hanna sent you a message in Skype for Business

So, based on my quick analysis of the ABIs, yes, there needs to be sign extension and truncation. 
David, could you produce a table of which cases need sign extension/truncation? (and if there are differences by architecture, that would be quite useful). Once you have such a table, please assign the bug back to… well me. And I’ll take a look today/Monday.

Thanks,
David

From: Fadi Hanna 
Sent: Thursday, July 13, 2017 9:10 PM
To: David Gillies <dgillies@microsoft.com>; David Wrighton <davidwr@microsoft.com>
Subject: Re: David Gillies sent you a message in Skype for Business-Fadi Hanna sent you a message in Skype for Business

There is a calling convention involved, but I am now OOF so I can't really look into it.

DavidWr, could you please check if the converter needs to sign-extend negative 8 or 16 bit numbers? (The converter today doesn't really look at primitive types in these cases, in order to do arithmetics or sign extensions... maybe the initial callers need to do so, before we even get into any converter logic... IMHO I don't think the converter needs to do any arithmetics or sign extensions. It just does buffer copying/allocations, and I'd prefer we keep it that way)

The converter also does the same for all architecture. x86 and x64 are not affected by this, so maybe codegen explicitly does sign extensions there?

Sent using OWA for iPhone 
________________________________________
From: David Gillies <dgillies@microsoft.com>
Sent: Thursday, July 13, 2017 4:20:36 PM
To: David Gillies; Fadi Hanna
Subject: David Gillies sent you a message in Skype for Business-Fadi Hanna sent you a message in Skype for Business 
 
Fadi Hanna 11:53 AM: 
hi David
David Gillies 11:53 AM: 
hi
Fadi Hanna 11:53 AM: 
i have a arm32 codegen bug with optimizations (ProjectN)
Fadi Hanna 11:53 AM: 
for this week's ZBB
Fadi Hanna 11:53 AM: 
i know exactly what the issue is
Fadi Hanna 11:53 AM: 
who should i assign the bug to?
David Gillies 11:53 AM: 
ok
David Gillies 11:54 AM: 
you can assign to me and I will triage and possibly re-assign.
David Gillies 11:54 AM: 
what sort of issue is it (briefly)?
Fadi Hanna 11:54 AM: 
signed byte subtraction
Fadi Hanna 11:55 AM: 
on chk, we have the following:
Fadi Hanna 11:55 AM: 
ldrsb r2,[r3]
Fadi Hanna 11:55 AM: 
ldrcb r3,[sp,#value]
Fadi Hanna 11:55 AM: 
sub r3, r2, r3
Fadi Hanna 11:55 AM: 
with optimizations, we have the following:
Fadi Hanna 11:56 AM: 
ldrsb r3,[r0]
Fadi Hanna 11:56 AM: 
sub r0,r3,r1
Fadi Hanna 11:57 AM: 
when values like 0x80 and 0, the subtraction puts ffffff80 in r0. the return type of the function is int, so the preceding fffff's mess up binary searches
Fadi Hanna 11:58 AM: 
System.SByte.CompareTo()
David Gillies 11:58 AM: 
hmmm...ok.  If you have intermediates etc you can point to that would be a big help
Fadi Hanna 11:58 AM: 
sure
Fadi Hanna 11:59 AM: 
i'll assign the GIT bug to you, and IM you a share with intermediates (and the ilc input folder)
David Gillies 12:00 PM: 
ok, thanks.  
Fadi Hanna 12:17 PM: 
Here's the share:
Fadi Hanna 12:17 PM: 
\\fadim-wks\Repro 
Fadi Hanna 12:17 PM: 
the _INT folder contains the intermediates
David Gillies 12:18 PM: 
alright thanks...
Fadi Hanna 12:18 PM: 
testResults.xml shows all the tests that failed. it's not just SByte, but looks like all signed subtractions at edge cases
David Gillies 12:18 PM: 
so let me make sure I understand the issue...
David Gillies 12:19 PM: 
in the opt case we are r0 get's a sign extended result that is not there in the no-opt case?
Fadi Hanna 12:19 PM: 
i believe so yes
David Gillies 12:20 PM: 
and what about the no-opt sequence prevents this (assuming it's the same values)?
David Gillies 12:20 PM: 
(could not find ldrcb in the instruction manual)
Fadi Hanna 12:21 PM: 
sorry, i meant ldrsb
Fadi Hanna 12:21 PM: 
(typo)
David Gillies 12:21 PM: 
seems like the result would be the same for those same values, though?
Fadi Hanna 12:22 PM: 
when doing 0-0x80, the non-opt call returns 0x80. the opt call returns ffffff80
Fadi Hanna 12:23 PM: 
there's also an issue with 16 bits (See testResults.xml)
David Gillies 12:24 PM: 
ok I'll have a deeper look.
Fadi Hanna 12:24 PM: 
i wrote a small text file with instructions on how to repro
David Gillies 12:24 PM: 
thanks!
Fadi Hanna 12:25 PM: 
you can recompile ILCInputFolder any time. that's the input IL images
Fadi Hanna 12:26 PM: 
do you have a github account so i can assign the issue to you?
David Gillies 12:27 PM: 
I think my id is dgilliesMS...our team is not really engaged there very heavily :-)
Fadi Hanna 12:28 PM: 
I couldn't find that id :)
Fadi Hanna 12:28 PM: 
i'll keep the issue assigned to me, no worries
Fadi Hanna 12:28 PM: 
that's bug is for this weeks ZBB
Fadi Hanna 12:28 PM: 
and here's a link to it:
Fadi Hanna 12:28 PM: 
https://github.com/dotnet/corefx/issues/21379 
David Gillies 12:28 PM: 
understood.  I'll have a look at it this afternoon
Fadi Hanna 12:29 PM: 
thanks David!
David Gillies 3:58 PM: 
Hi,
David Gillies 3:58 PM: 
I've had a chance to look at this a bit and I think the problem is that the incoming signed int parameter is not sign extended.
David Gillies 4:00 PM: 
that is, comes in as 0x80 and should be 0xffffff80.  It is only by the luck of the no-opt case that it goes ahead and sign extends the value from local store/load combo
David Gillies 4:01 PM: 
Is there a calling convention converter involved or some such?
David Gillies 4:02 PM: 
I'm not set up to run this, I was wondering if you could verify ?
David Gillies 4:18 PM: 
(incoming signed byte parameter, that is).

**Comment by fadimounir** [comment]
@Jiayili1 Can you please confirm that this test is now passing on ARM? The fix for this issue has been checked-in to the ProjectN branch.
If the tests pass, we can close the issue.

**Comment by safern** [comment]
@fadimounir https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Filc~2F/build/20170721.03/workItem/System.Runtime.Tests.Execution/analysis/xunit/System.Tests.ArrayTests~2FBinarySearch_SZArray%3CSByte%3E(array:%20%5B-128,%200,%200,%20127%5D,%20index:%201,%20length:%203,%20value:%20-128,%20comparer:%20null,%20expected:%20-2)

The tests just failed in the latest build. When was the fixed checked in into ProjectN?

**Comment by fadimounir** [comment]
@safern it was checked in yesterday 7:27pm. I think tomorrow's test results would be the ones that are interesting to check. Today's results are very unlikely to use the fix.

**Comment by safern** [comment]
Yes, the official builds happen at 6pm everyday so it should be picked up by corefx tomorrow morning, so I will keep an eye on them over the weekend.

**Comment by davidwrighton** [comment]
Official builds are not done Friday/Saturday night, so today should be the first build with the fix.

**Comment by danmosemsft** [comment]
This is apparently not failing any more in the UWP branch
https://mc.dot.net/#/product/netcore/uwp60/source/official~2Fcorefx~2Frelease~2Fuwp6.0~2F/type/test~2Ffunctional~2Filc~2F/build/20170727.01
