### ISSUE TITLE
System.Net.Http.dll should throw NotImplementedException instead of DllNotFoundException

### ISSUE THREAD

**Issue by ChengTian** [dotnet/corefx#2155]
When sending HTTP request with HttpClient on CoreCLR + *nix, the following exception is thrown:
```
Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'winhttp.dll': Error 126 (Exception from HRESULT: 0x8007007E)
   at System.Net.Http.Interop.WinHttpSetStatusCallback(SafeInternetHandle handle, WINHTTP_STATUS_CALLBACK callback, UInt32 notificationFlags, IntPtr reserved)
   at System.Net.Http.WinHttpHandler.SetStatusCallback(SafeInternetHandle requestHandle, WINHTTP_STATUS_CALLBACK callback)
   at System.Net.Http.WinHttpHandler.<StartRequest>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
libc++abi.dylib: terminating with uncaught exception of type PAL_SEHException
Abort trap: 6
```

It is better to use a more friendly exception.

**Comment by davidsh** [comment]
This will improve once PR #2149 is completed.

**Comment by davidsh** [comment]
@ChengTian This should be fixed now.  Can you confirm?  If so, this issue can be closed.

**Comment by ChengTian** [comment]
@davidsh This still reproduces with 4.0.0-beta-23107

**Comment by davidsh** [comment]
/cc @ericstj - Please comment on this.

@ChengTian Where are you getting the NuGet packages from?  The most current packages for System.Net.* are on dotnet-corefx:
https://www.myget.org/gallery/dotnet-core

Also, I think there is a an issue where platform specific binaries are not being put into the packages. So, even though we fixed this in the *Unix builds of System.Net.Http, the "Windows" version of the DLL is still being used.  If the proper *Unix version of the DLL was being used, then you would not get "DLL Not Found" but rather "PlatformNotSupportedException".

**Comment by ericstj** [comment]
We don't have *nix packages yet.  That work is still pending.  /cc @stephentoub @ellismg

**Comment by ChengTian** [comment]
@davidsh , I checked time stamp of packages on https://www.myget.org/gallery/dotnet-core, they have been there for weeks. So I am using packages from http://myget.org/gallery/aspnetvnext

**Comment by sandorfr** [comment]
I'm facing the same issue with beta7 on OSX. Is there a workaround?

**Comment by timothy-shields** [comment]
@davidsh I'm trying to use `HttpClient` in `dnxcore50` code running on Ubuntu 14.04 LTS.  I get the same exception: `Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'winhttp.dll': Error 126 (Exception from HRESULT: 0x8007007E)`.  Is there no support yet for making HTTP requests on Linux?  Or am I doing something wrong?

**Comment by davidsh** [comment]
If you're using the binary packages from NuGet or other feeds, then non-Windows platforms are NOT supported.  The packages only contain Windows binaries.

If you want to try out cross-platform stuff, you need to build from sources directly from GitHub CoreFx repo.

Provding cross-platform binaries in the NuGet packages is still a few weeks away.  @ericstj can comment on that.

**Comment by timothy-shields** [comment]
@ericstj Do you have an estimate of when `HttpClient` support we be available on Linux?

**Comment by tushargupta51** [comment]
I am hitting the same issue, both on linux and mac, when using beta7 bits

I am running a coreclr web application on mac using coreclr runtime. It builds fine using "dnu build" but when I start the application using "dnx kestrel" and loads the url (localhost:5002), it gives this exception:
Tushars-MacBook-Pro:WebApplication6 tushargupta$ dnx kestrel
Application started. Press Ctrl+C to shut down.

Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'winhttp.dll': The specified module could not be found.
(Exception from HRESULT: 0x8007007E)
at Interop.WinHttp.WinHttpSetStatusCallback(SafeWinHttpHandle handle, WINHTTP_STATUS_CALLBACK callback, UInt32 notificationFlags, IntPtr reserved)
at System.Net.Http.WinHttpHandler.SetStatusCallback(SafeWinHttpHandle requestHandle, WINHTTP_STATUS_CALLBACK callback)
at System.Net.Http.WinHttpHandler.d__120.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.AsyncMethodBuilderCore.b__4(Object state)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
at System.Threading.ThreadPoolWorkQueue.Dispatch()
libc++abi.dylib: terminating with uncaught exception of type PAL_SEHException
Abort trap: 6

**Comment by davidsh** [comment]
Short summary of this is that xplat binary packages DO NOT YET support non-Windows.  That work is ongoing still.

**Comment by sandorfr** [comment]
I guess we have to be patient let's hope it will be there for bet 8 in 2 weeks.

**Comment by timothy-shields** [comment]
In case anybody else needs a temporary replacement, I have quickly implemented an `HttpMessageHandler` that just calls `curl`.  Do whatever you want with it, there are no legal guarantees, etc.  http://freetexthost.com/eihagy6hho  Hopefully it will hold you over until things are working.

**Comment by sandorfr** [comment]
@timothy-shields  so sweet, thank you :).

**Comment by davidsh** [comment]
This should be fixed now in ASP.NET Beta8

**Comment by naveensrinivasan** [comment]
I tried it with the latest beta  and it still fails


```
c:\code\coreclr>set DNX_FEED=https://www.myget.org/f/aspnebeta8

c:\code\coreclr>dnvm upgrade -u
Determining latest version
'dnx-clr-win-x86.1.0.0-rc1-15838' is already installed.
Adding C:\Users\nsrinivasan\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-15838\bin to
 process PATH
Adding C:\Users\nsrinivasan\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-15838\bin to
 user PATH
Updating alias 'default' to 'dnx-clr-win-x86.1.0.0-rc1-15838'

c:\code\coreclr>dnvm list

Active Version         Runtime Architecture Location
------ -------         ------- ------------ --------
       1.0.0-beta5     clr     x64          C:\Users\nsrinivasan\.dnx\runtimes
       1.0.0-beta5     clr     x86          C:\Users\nsrinivasan\.dnx\runtimes
       1.0.0-beta5     coreclr x64          C:\Users\nsrinivasan\.dnx\runtimes
       1.0.0-beta5     coreclr x86          C:\Users\nsrinivasan\.dnx\runtimes
  *    1.0.0-rc1-15838 clr     x86          C:\Users\nsrinivasan\.dnx\runtimes
       1.0.0-rc1-15838 coreclr x64          C:\Users\nsrinivasan\.dnx\runtimes
       1.0.0-rc1-15838 coreclr x86          C:\Users\nsrinivasan\.dnx\runtimes



c:\code\coreclr>dnu restore
Microsoft .NET Development Utility Clr-x86-1.0.0-rc1-15838

  CACHE https://www.nuget.org/api/v2/
  CACHE https://api.nuget.org/v3/index.json
Restoring packages for c:\code\coreclr\project.json
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='System.Console'
  CACHE https://api.nuget.org/v3-flatcontainer/system.console/index.json
Unable to locate Dependency Microsoft.Net.Http
Writing lock file c:\code\coreclr\project.lock.json
Restore complete, 794ms elapsed

Errors in c:\code\coreclr\project.json
    Unable to locate Dependency Microsoft.Net.Http

NuGet Config files used:
    C:\Users\nsrinivasan\AppData\Roaming\NuGet\nuget.config

Feeds used:
    https://www.nuget.org/api/v2/
    https://api.nuget.org/v3-flatcontainer/

c:\code\coreclr>dnu restore
Microsoft .NET Development Utility Clr-x86-1.0.0-rc1-15838

  CACHE https://www.nuget.org/api/v2/
  CACHE https://api.nuget.org/v3/index.json
  GET https://www.myget.org/F/aspnetbeta8/api/v3/index.json
  OK https://www.myget.org/F/aspnetbeta8/api/v3/index.json 3005ms
Restoring packages for c:\code\coreclr\project.json
  GET https://www.nuget.org/api/v2/FindPackagesById()?id='System.Console'
  GET https://api.nuget.org/v3-flatcontainer/system.console/index.json
  GET https://www.myget.org/F/aspnetbeta8/api/v3/flatcontainer/system.console/in
dex.json
  OK https://www.nuget.org/api/v2/FindPackagesById()?id='System.Console' 295ms
  OK https://www.myget.org/F/aspnetbeta8/api/v3/flatcontainer/system.console/ind
ex.json 507ms
  OK https://api.nuget.org/v3-flatcontainer/system.console/index.json 1179ms
  GET https://www.myget.org/F/aspnetbeta8/api/v3/flatcontainer/system.console/4.
0.0-beta-23409/system.console.4.0.0-beta-23409.nupkg
  OK https://www.myget.org/F/aspnetbeta8/api/v3/flatcontainer/system.console/4.0
.0-beta-23409/system.console.4.0.0-beta-23409.nupkg 1533ms
  GET https://www.nuget.org/api/v2/FindPackagesById()?id='System.Runtime'
  GET https://api.nuget.org/v3-flatcontainer/system.runtime/index.json
  GET https://www.myget.org/F/aspnetbeta8/api/v3/flatcontainer/system.runtime/in
dex.json
  OK https://www.nuget.org/api/v2/FindPackagesById()?id='System.Runtime' 83ms
  GET https://www.nuget.org/api/v2/package/System.Runtime/4.0.0
  OK https://api.nuget.org/v3-flatcontainer/system.runtime/index.json 195ms
  OK https://www.myget.org/F/aspnetbeta8/api/v3/flatcontainer/system.runtime/ind
ex.json 195ms
  OK https://www.nuget.org/api/v2/package/System.Runtime/4.0.0 1615ms
  GET https://www.nuget.org/api/v2/FindPackagesById()?id='runtime.win7.System.Co
nsole'
  GET https://api.nuget.org/v3-flatcontainer/runtime.win7.system.console/index.j
son
  GET https://www.myget.org/F/aspnetbeta8/api/v3/flatcontainer/runtime.win7.syst
em.console/index.json
  OK https://www.nuget.org/api/v2/FindPackagesById()?id='runtime.win7.System.Con
sole' 60ms
  NotFound https://api.nuget.org/v3-flatcontainer/runtime.win7.system.console/in
dex.json 149ms
  OK https://www.myget.org/F/aspnetbeta8/api/v3/flatcontainer/runtime.win7.syste
m.console/index.json 182ms
  GET https://www.myget.org/F/aspnetbeta8/api/v3/flatcontainer/runtime.win7.syst
em.console/4.0.0-beta-23409/runtime.win7.system.console.4.0.0-beta-23409.nupkg
  OK https://www.myget.org/F/aspnetbeta8/api/v3/flatcontainer/runtime.win7.syste
m.console/4.0.0-beta-23409/runtime.win7.system.console.4.0.0-beta-23409.nupkg 10
19ms
Unable to locate Dependency Microsoft.Net.Http
Installing System.Console.4.0.0-beta-23409
Installing System.Runtime.4.0.0
Installing runtime.win7.System.Console.4.0.0-beta-23409
Writing lock file c:\code\coreclr\project.lock.json
Restore complete, 7515ms elapsed

Errors in c:\code\coreclr\project.json
    Unable to locate Dependency Microsoft.Net.Http

NuGet Config files used:
    C:\Users\nsrinivasan\AppData\Roaming\NuGet\nuget.config

Feeds used:
    https://www.nuget.org/api/v2/
    https://api.nuget.org/v3-flatcontainer/
    https://www.myget.org/F/aspnetbeta8/api/v3/flatcontainer/

Installed:
    3 package(s) to C:\Users\nsrinivasan\.dnx\packages

c:\code\coreclr>

````

I am using the apnetbeta8

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageRestore>
    <add key="enabled" value="True" />
    <add key="automatic" value="True" />
  </packageRestore>
  <packageSources>
    <add key="Official NuGet Gallery" value="https://www.nuget.org/api/v2/" />
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    <add key="aspnetbeta8" value="https://www.myget.org/F/aspnetbeta8/api/v3/index.json" protocolVersion="3" />
  </packageSources>
  <activePackageSource>
    <add key="aspnetbeta8" value="https://www.myget.org/F/aspnetbeta8/api/v3/index.json" />
  </activePackageSource>
</configuration>
```

**Comment by davidsh** [comment]
@naveensrinivasan 
Is this on Windows on Linux?  This original issue was about the Linux version  not working correctly.  Your traces above show Windows OS.

**Comment by naveensrinivasan** [comment]
This is on windows. I tried on osx also.

**Comment by davidsh** [comment]
This issue tracked runtime xplat dependencies for Linux.

It sounds like you are having a different problem on Windows.

Please open up a NEW issue and open it up in the asp.net/dnx repo: https://github.com/aspnet/dnx

It looks like you are having some old packages being restored incorrectly.  Perhaps this is a package cache/corruption issue.  The DNX team would be best to troubleshoot this.

**Comment by FLGMwt** [comment]
If it helps anyone, I ran into this today using `"System.Net.Http" : "4.0.0"`, but I bumped it up to `4.3.0` and everything is good now
