### ISSUE TITLE
Core Tests (2.0.0): All work items have fireball issue for RHEL69

### ISSUE THREAD

**Issue by Jiayili1** [dotnet/corefx#23279]
Detail: https://mc.dot.net/#/product/netcore/200/source/official~2Fcorefx~2Frelease~2F2.0.0~2F/type/test~2Ffunctional~2Fcli~2F/build/20170815.02

Failed configurations:
Centos.73.Amd64-x64
Debian.87.Amd64-x64
RedHat.69.Amd64-x64
RedHat.72.Amd64-x64
RedHat.73.Amd64-x64
SLES.12.Amd64-x64
Ubuntu.1404.Amd64-x64
Ubuntu.1604.Amd64-x64
suse.422.amd64-x64

**Comment by danmosemsft** [comment]
ICU issue that @weshaggard is debugging

**Comment by weshaggard** [comment]
This should be fixed now.

**Comment by Jiayili1** [comment]
This issue is repro, detail: https://mc.dot.net/#/product/netcore/200/source/official~2Fcorefx~2Frelease~2F2.0.0-msrc~2F/type/test~2Ffunctional~2Fcli~2F/build/20170822.02

**Comment by Jiayili1** [comment]
This issue is still repro: https://mc.dot.net/#/product/netcore/200/source/official~2Fcorefx~2Frelease~2F2.0.0~2F/type/test~2Ffunctional~2Fcli~2F/build/20170829.01

**Comment by Jiayili1** [comment]
This issue still repro in 2.0.0 branch: https://mc.dot.net/#/product/netcore/200/source/official~2Fcorefx~2Frelease~2F2.0.0~2F/type/test~2Ffunctional~2Fcli~2F/build/20170906.01

**Comment by danmosemsft** [comment]
@weshaggard RH9 tests are still all broken in 2.0 so we have no "read" for this distro. Could you please take a look? 

```
2017-09-05 20:22:27,035: INFO: proc(54): run_and_log_output: Output: downloaded dumpling.py
2017-09-05 20:22:27,035: INFO: proc(54): run_and_log_output: Output: total elapsed time 0:00:00.162161
2017-09-05 20:22:27,073: INFO: proc(54): run_and_log_output: Output: chmod: cannot access `/home/helixbot/dotnetbuild/work/87655c9b-fc34-4d17-a795-aac600095c8c/Payload/dotnet': No such file or directory
```

**Comment by weshaggard** [comment]
@janvorli @smile21prc I suspect they have the same issue we faced in master. We need to probably port those changes to release/2.0.0

**Comment by danmosemsft** [comment]
@janvorli @smile21prc who can port this? (don't know which change)

**Comment by danmosemsft** [comment]
Sorry, I guess I mean -- which change needs to be ported by someone?

**Comment by Jiayili1** [comment]
still repro, have fireball issue on **RedHat.69.Amd64-x64**, detail: https://mc.dot.net/#/product/netcore/200/source/official~2Fcorefx~2Frelease~2F2.0.0~2F/type/test~2Ffunctional~2Fcli~2F/build/20170908.01

**Comment by janvorli** [comment]
@smile21prc I can see in the log that the tests are failing due to this:
`chmod: cannot access `/home/helixbot/dotnetbuild/work/c3b5689d-e197-412a-93f8-172cef93dcb9/Payload/dotnet': No such file or directory
`
I think we had the same issue with the master builds before, but I don't remember what was the fix for this one and cannot find it in our conversations. Do you remember that?

**Comment by danmosemsft** [comment]
@smile21prc  ?

**Comment by smile21prc** [comment]
Didn't notice this thread until jan pinged me today. The logs contains all test artifacts is:
https://dotnetbuilddrops.blob.core.windows.net/build-32c392f26fb74948ae072f4937abc328/TestList.json?sv=2015-04-05&sr=c&sig=LjYI3MyqpsT63fLLxIxfh9LsVj3evs8r7CGkPHDe%2F%2BU%3D&st=2017-09-08T19%3A34%3A28.1220310Z&se=2017-10-08T19%3A34%3A28.1220410Z&sp=r 

The logs to build those tests are:
https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build/index?buildId=978613&_a=summary

**Comment by janvorli** [comment]
I have looked at the artifacts and the corresponding test-runtime-netcoreapp-Linux-Debug-x64.zip  at https://dotnetbuilddrops.blob.core.windows.net/build-32c392f26fb74948ae072f4937abc328/test-runtime-netcoreapp-Linux-Debug-x64.zip?sv=2015-04-05&sr=c&sig=LjYI3MyqpsT63fLLxIxfh9LsVj3evs8r7CGkPHDe%2F%2BU%3D&st=2017-09-08T19%3A34%3A28.1220310Z&se=2017-10-08T19%3A34%3A28.1220410Z&sp=r 
is missing the dotnet tool and host folder in its root.

Now that I've seen that, I've just remembered that when I was doing the bringup, when the runtime.rhel.6-x64.Microsoft.NETCore.DotNetHost  of the appropriate version was missing on Nuget, the build passed without any error or even a warning, but the dotnet tool and the host folder were missing in the test runtime folder. 

I'll try to build release/2.0.0 corefx locally to see if the same thing happens.

**Comment by janvorli** [comment]
I have tried to build corefx 2.0.0 locally and the same thing happens - the test runtime folder doesn't contain the dotnet binary and host folder after the build completes. There is no error or warning during the build.

**Comment by janvorli** [comment]
Ok, so the problem is that we don't have runtime.rhel.6-x64.Microsoft.NETCore.DotNetHost and runtime.rhel.6-x64.Microsoft.NETCore.DotNetHostPolicy packages version 2.0.0-preview2-25310-02 on myget. We only have versions 2.1.0 and newer over there. So it is a chicken and egg problem. @weshaggard what would be the best way to solve the issue? Can we build these packages locally and push them to the myget somehow? I guess you have probably done something like that when we kicked off the 2.1.0 builds, right?

**Comment by weshaggard** [comment]
@janvorli I think we just need to get this PR https://github.com/dotnet/corefx/pull/23536 into release/2.0.0 branch.

**Comment by danmosemsft** [comment]
fixed
