### ISSUE TITLE
Investigate optimizations for vectorized Span<byte> {Last}IndexOf{Any} APIs

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#25893]
From https://github.com/dotnet/corefx/pull/25848#discussion_r156750679

Consider avoiding the memory alignment checks and only loop byte at a time until we get Vector.Count aligned.

The APIs to consider optimizing (for typeof(T) == byte):
```C#
public static int IndexOf<T>(this Span<T> span, T value) where T : IEquatable<T> { throw null; }
public static int IndexOf<T>(this Span<T> span, ReadOnlySpan<T> value) where T : IEquatable<T> { throw null; }

public static int IndexOfAny(this Span<byte> span, byte value0, byte value1) { throw null; }
public static int IndexOfAny(this Span<byte> span, byte value0, byte value1, byte value2) { throw null; }
public static int IndexOfAny(this Span<byte> span, ReadOnlySpan<byte> values) { throw null; }

public static int LastIndexOf<T>(this Span<T> span, T value) where T : IEquatable<T> { throw null; }
public static int LastIndexOf<T>(this Span<T> span, ReadOnlySpan<T> value) where T : IEquatable<T> { throw null; }

public static int LastIndexOfAny<T>(this Span<T> span, T value0, T value1) where T : IEquatable<T> { throw null; }
public static int LastIndexOfAny<T>(this Span<T> span, T value0, T value1, T value2) where T : IEquatable<T> { throw null; }
public static int LastIndexOfAny<T>(this Span<T> span, ReadOnlySpan<T> values) where T : IEquatable<T> { throw null; }
```

+ the equivalent ReadOnlySpan extension methods

See current implementation here:
https://github.com/dotnet/corefx/blob/c20881a8ea94a40e1f1f98f79ffdef9f6fc87c44/src/System.Memory/src/System/SpanHelpers.byte.cs#L91

cc @KrzysztofCwalina, @GrabYourPitchforks, @benaadams

**Comment by stephentoub** [comment]
I believe this has been addressed, e.g. https://github.com/dotnet/coreclr/pulls?utf8=%E2%9C%93&q=is:pr+indexofany.  If not, please re-open.

**Comment by ahsonkhan** [comment]
I believe this particular issue still exists in the current implementation, but it's an uncommon edge case with not a significant impact.

> If you go to sequential scan from here, after finishing the sequential scan, you will execute if (Vector.IsHardwareAccelerated && ((int)(byte*)index > 0)) gain, which will never evaluate to true, i.e. you will execute the check twice. Is this the best way to organize the code?

One extra check if the value was not found.
https://github.com/dotnet/corefx/blob/fd4f870a9da036458309d0b833a2cd6ad5f354df/src/Common/src/CoreLib/System/SpanHelpers.Byte.cs#L1158
https://github.com/dotnet/corefx/blob/fd4f870a9da036458309d0b833a2cd6ad5f354df/src/Common/src/CoreLib/System/SpanHelpers.Byte.cs#L1131

@benaadams, what do you think? Even in a PR like this: https://github.com/dotnet/coreclr/pull/22877,  we have this extra check:
https://github.com/dotnet/coreclr/blob/b0646fa843655f3d4c3e044e431ae777bc9ce1c9/src/System.Private.CoreLib/shared/System/SpanHelpers.Char.cs#L208
https://github.com/dotnet/coreclr/blob/b0646fa843655f3d4c3e044e431ae777bc9ce1c9/src/System.Private.CoreLib/shared/System/SpanHelpers.Char.cs#L180

**Comment by benaadams** [comment]
Not sure if there is a way around it without extra code duplication (single pass, total length less than vector)? 

Its a checking so see if it was doing alignment (first pass) or finishing (last pass)?
