### ISSUE TITLE
XmlReader.Create thrown ArgumentOutOfRangeException on string with diacritics

### ISSUE THREAD

**Issue by jakubsuchybio** [dotnet/corefx#26210]
Hi,
I am in the process of migration our Windows game server into Linux. I already ported it to .NET Standard 2.0, but I am having an issue here.
When I try to read .xml files that have diacritics in the filename, then it throws on me.
This code, ran at linux:

```c#
using System;
using System.Xml;

namespace test
{
    class Program
    {
        static void Main(string[] args)
        {
            using (XmlReader.Create("/mnt/c/dev/csharp/manawydan-git/Server/RunUOPro/Data/Interaction/npc/Hledání draka.xml"))
            {
                Console.WriteLine("hi");
            }

        }
    }
}
```

Throws:
```
Unhandled Exception: System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at System.Uri.CreateHostStringHelper(String str, UInt16 idx, UInt16 end, Flags& flags, String& scopeId)
   at System.Uri.CreateHostString()
   at System.Uri.EnsureHostString(Boolean allowDnsOptimization)
   at System.Uri.GetComponentsHelper(UriComponents uriComponents, UriFormat uriFormat)
   at System.Uri.ToString()
   at System.Xml.XmlTextReaderImpl..ctor(String uriStr, XmlReaderSettings settings, XmlParserContext context, XmlResolver uriResolver)
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at System.Xml.XmlReader.Create(String inputUri)
   at test.Program.Main(String[] args) in /mnt/c/dev/csharp/manawydan-git/test/Program.cs:line 11
```
I tried to debug the source of .NET Core and got to Uri.cs:4768 with line:
```_string.CopyTo(_info.Offset.Path, dest, end, _info.Offset.Query - _info.Offset.Path);```
Inside this It throws that exception on string.cs:128 arguments to the CopyTo method are:
```
sourceIndex	5	int
destination	{char[94]}	char[]
destinationIndex	8	int
count	88	int
```
With them the condition ```destinationIndex > destination.Length - count``` fails because 8 > 94-88 => 8 > 6.

My guess is, that Uri badly calculates the length of a string because of those diacritics characters.

I will try to remove diacritics from my xml filenames so that our server can start properly, but this is cumbersome at the very least.

[EDIT] Add C# syntax highlighting by @karelz

**Comment by karelz** [comment]
Can you try the same repro on Windows .NET Core 2.0?
Can you please try to isolate the repro just to `Uri`? (without XML reader)

Could it be related to #25820?

**Comment by danmosemsft** [comment]
It would be great to try it with latest 2.1 bits - can be gotten from https://github.com/dotnet/cli - as #25820 was fixed post 2.0 I think.

**Comment by jakubsuchybio** [comment]
You can try this repro code on Windows. It still crashes. When I use C:/ it doesn't crash, but with /mnt it does.
I tried 2.1.3 and still the same issue.

**Comment by jakubsuchybio** [comment]
So the XmlReader has some XmlUrlResolver, which creates Uri here:
![](https://i.imgur.com/7vsfUZA.jpg)
and then the uri looks inside like this:
![](https://i.imgur.com/cLGiPam.png)
which then crashes here:
![](https://i.imgur.com/qaNxBTK.jpg)

More insights are too much for me. But from what I can see there is not enought space in that dest array to copy to... And that is because of bad canclulaction of count from which is that array initialized. And that count is dependant upon (UriFormat)32767 whatever that means...

**Comment by danmosemsft** [comment]
cc @rmkerr

**Comment by rmkerr** [comment]
Hey @jakubsuchybio could you give the repro a try on the latest nightly build? I haven't been able to repro on my machine, and I think that it may have been resolved by #25993. The description there is specific to how the error occurs with windows style paths, but I think the same fundamental problem might be occurring here. I'd like to do some testing to be sure, but here's my theory. Be warned, it's just idle speculation from hereon out:

Notice how in screenshot 2 the host property is an empty string, meaning it will fail the DNS host processing path and fall through to the UNC host processing path. Up until #25993 that path sometimes dropped Unicode characters, leading to an invalid internal state for the URI. The internal string representing the canonical URI would contain everything up to the Unicode characters, but the integer storing the index of the end of the authority would be set as it was before normalization to the end of the string including the Unicode characters. At some point the difference between the measured length of the URI and the actual length leads to problems like the one you saw here.

**Comment by jakubsuchybio** [comment]
Hi, I am kinda stuck on installing nightly build.
I went by https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/dogfooding.md but I am not even able to install that .deb package because of asp core dependencies. :/ 
```
biosek@BIO-PC:~/dotnet$ sudo dpkg -i dotnet-sdk-latest-x64.deb
[sudo] password for biosek:
(Reading database ... 26793 files and directories currently installed.)
Preparing to unpack dotnet-sdk-latest-x64.deb ...
Unpacking dotnet-sdk-2.2.0-preview1-007946 (2.2.0-preview1-007946-1) over (2.2.0-preview1-007946-1) ...
dpkg: dependency problems prevent configuration of dotnet-sdk-2.2.0-preview1-007946:
 dotnet-sdk-2.2.0-preview1-007946 depends on aspnetcore-runtime-2.1.0-preview1-28042; however:
  Package aspnetcore-runtime-2.1.0-preview1-28042 is not installed.
 dotnet-sdk-2.2.0-preview1-007946 depends on dotnet-runtime-2.1.0-preview1-26112-04; however:
  Package dotnet-runtime-2.1.0-preview1-26112-04 is not installed.

dpkg: error processing package dotnet-sdk-2.2.0-preview1-007946 (--install):
 dependency problems - leaving unconfigured
Processing triggers for man-db (2.7.5-1) ...
Errors were encountered while processing:
 dotnet-sdk-2.2.0-preview1-007946
biosek@BIO-PC:~/dotnet$ dotnet
dotnet: command not found
```
Any help please?

**Comment by karelz** [comment]
@jakubsuchybio let's please take it to another issue. It is not related to this one. Doesn't even fit CoreFX repo well, but we can start here, until we find the right place.

**Comment by jakubsuchybio** [comment]
@rmkerr Could you please point me to some guide or help me how to install nightly build?
As you can see I have troubles with it to repro my issue on that nightly version..
Thx
@karelz I don't even know if I am installing that nightly build correctly, so dunno if this is an actual issue...
.NET Core and it's CLI aren't that easy to grasp and the guides doesn't help much :/

**Comment by karelz** [comment]
@jakubsuchybio understood, still worth a new issue - if it is unclear in docs, we should fix it. We should not mingle it with specific issues, it just creates clutter. People who know how installer works may be different people than the area experts :)

**Comment by jakubsuchybio** [comment]
@karelz So you suggest creating issue at https://github.com/dotnet/cli ? Or where does this falls into?
In really simplistic way:
- CLI is just a 'dotnet' without any runtime and any libraries (sdk)
- corefx is actual implementation of .net core so it is the whole runtime + sdk

So when I am installing dotnet it must be bundled as CLI + corefx no? Therefore where should I put this new issue if it is about dependencies for this bundle? Who maintains putting it all together into one package?

**Comment by karelz** [comment]
@jakubsuchybio this repo is fine - after all you're using dogfooding instructions from here. We can move it later if needed.

**Comment by rmkerr** [comment]
I wish I could offer more help, but I'm not familiar with the install process on Linux. I'm going to give the repro another try though. I only just saw that it fails only with /mnt and not with C:\, which I didn't take into account earlier. I'll take another look at it.

**Comment by karelz** [comment]
@wfurt could you help here?

**Comment by wfurt** [comment]
I was able to run this using cli 2.2.0-preview1-007925 on Ubuntu. 
I used /tmp instead of /mnt but I should not matter. 
I tested LANG=C as well as LANG=en_US.UTF-8

The /mnt prefix suggests it is some network share or different volume...???  

BTW as far as the testing @jakubsuchybio I normally use tar.gz and than simply
~/latest/dotnet run
(and I modified my project to  netcoreapp2.1 or you can use dotnet --fx-version  2.1.0-preview1-26109-01 to force specific runtime version)
Let me know if that gives you any grief)

**Comment by wfurt** [comment]
BTW I do get same exception when I try to run it with 2.0.3

**Comment by kasper3** [comment]
This seems to be fixed in 2.1 preview.

1. Install docker then run 

```sh
docker run -it microsoft/dotnet:2.0-sdk
```

2. in the container create a file having name with diacritics

```sh
touch /Hledání.xml
```

3. create a dotnet app

```sh
dotnet new console -n xmltest
cd $_
```

4. edit Program.cs and replace the content with

```c#
using System;
using System.Xml;

namespace test
{
    class Program
    {
        static void Main(string[] args)
        {
            using (XmlReader.Create("/Hledán.xml"))
            {
                Console.WriteLine("hi");
            }

        }
    }
}
```

4. run

```sh
dotnet run
```

```
Unhandled Exception: System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at System.Uri.CreateHostStringHelper(String str, UInt16 idx, UInt16 end, Flags& flags, String& scopeId)
   at System.Uri.CreateHostString()
   at System.Uri.EnsureHostString(Boolean allowDnsOptimization)
   at System.Uri.GetComponentsHelper(UriComponents uriComponents, UriFormat uriFormat)
   at System.Uri.ToString()
   at System.Xml.XmlTextReaderImpl..ctor(String uriStr, XmlReaderSettings settings, XmlParserContext context, XmlResolver uriResolver)
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at System.Xml.XmlReader.Create(String inputUri)
   at test.Program.Main(String[] args) in /xmltest/Program.cs:line 10
```

---

now test with 2.1

```sh
docker run -it microsoft/dotnet:2.1-sdk
```
and repeat steps 2 to 4. `hi` will be printed.

**Comment by karelz** [comment]
@kasper3 thanks for validation on 2.1! That is very useful!
Closing as fixed.
