### ISSUE TITLE
 Need two Http requests to set cookies

### ISSUE THREAD

**Issue by Tratcher** [dotnet/corefx#26722]
_From @tanyado on January 31, 2018 22:21_

In .NET Core, I have to send a two http requests manually – only the second post request will succeed.

    HttpClientHandler handler = new HttpClientHandler();
    handler.Credentials = new NetworkCredential(userName, userPass);

    HttpClient client = new HttpClient(handler);
    client.BaseAddress = new Uri(baseUri);
 
    // PROBLEM HERE: 
    await client.PostAsync(requestUri, null); // The extra post request to set cookie
    var response = await client.PostAsync(requestUri, new StringContent(Body(), Encoding.UTF8, "application/json"));

The server sets a cookie on the initial 401 challenge and rejects the subsequent credentialed request if it lacks this cookie.

Fiddler Traces are in this folder: https://microsoft-my.sharepoint.com/:f:/p/tad/Ehuec61zdD9Fp1Vlf6QI718BynEnS-HF3tL4w9FXGgH7Eg?e=tsH1fU

_Copied from original issue: aspnet/Home#2841_

**Comment by Tratcher** [comment]
_From @Eilon on January 31, 2018 22:58_

Hi @tanyado , is this an issue with HttpClient or with ASP.NET Core?

cc @Tratcher in case you have any idea on this?

**Comment by davidsh** [comment]
>The server sets a cookie on the initial 401 challenge and rejects the subsequent credentialed request if it lacks this cookie.

This is an issue with WinHttpHandler.  The .NET layer doesn't seem the initial 401 since it is handled at the native WinHTTP layer.  So, it doesn't seem any cookies attached to the initial 401.  Fixing this requires some changes in WinHttpHandler to get notified of 401's and be able to grab the incoming 'Set-Cookie' headers.

**Comment by geoffkizer** [comment]
Linked issue #26986 was fixed, so I believe this should be fixed now.

**Comment by davidsh** [comment]
This shouldn't be closed.  The linked issue was closed because it was a duplicate of another bug, #26722.  But the root cause of this is in WinHttpHandler and wasn't fixed.

**Comment by geoffkizer** [comment]
Whoops, sorry, you're right.

**Comment by davidsh** [comment]
Since SocketsHttpHandler is the default HTTP stack, fixing this problem in WinHttpHandler is less of a priority.
