### ISSUE TITLE
System.MissingMethodException : Method not found: 'Void System.IO.Compression.ZipFileExtensions.ExtractToFile(System.IO.Compression.ZipArchiveEntry, System.String, Boolean)'

### ISSUE THREAD

**Issue by xaviergxf** [dotnet/corefx#26996]
I'm having the following error when targetting netappcore2.0 and net471:

System.MissingMethodException : Method not found: 'Void System.IO.Compression.ZipFileExtensions.ExtractToFile(System.IO.Compression.ZipArchiveEntry, System.String, Boolean)'.

Is this a new bug? Is there any workaround available?

Thanks.

**Comment by danmosemsft** [comment]
@joperezr is this one of the known issues in 471?

**Comment by joperezr** [comment]
Yes, I believe the problem here is that you are missing a binding redirect to System.IO.Compression.ZipFile. This will be automatically generated for you when we ship VS 15.6, but for the time being, can you please try adding the following binding redirect manually to your net471's app.config?
```xml
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.IO.Compression.ZipFile" culture="neutral" publicKeyToken="b77a5c561934e089" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.3.0" newVersion="4.0.3.0" />
      </dependentAssembly>
    </assemblyBinding>
```

**Comment by joperezr** [comment]
Let us know if that binding redirect fixes your issue.

**Comment by xaviergxf** [comment]
Hi @joperezr, thanks for the workaround. If this is a problem with vs, then i could use the cli instead? Thanks

**Comment by ianhays** [comment]
@joperezr @xaviergxf have either of you tried it using the [latest VS 15.6 preview version](https://blogs.msdn.microsoft.com/visualstudio/2018/02/08/visual-studio-2017-version-15-6-preview-4/)

**Comment by xaviergxf** [comment]
@ianhays i didn't tried. I try my best not to use something in preview that we'll damage my productivity :)

**Comment by ianhays** [comment]
@xaviergxf totally understand, thanks for the quick response :) 

I made a simple app on the latest VS preview version and couldn't repro the issue, but I wanted to make sure I'm testing the right thing. Do you have a small repro program or example that you could provide that I can test with the latest VS Preview to make sure this has been resolved?

**Comment by xaviergxf** [comment]
@ianhays here's the demo. 
[ConsoleApp5.zip](https://github.com/dotnet/corefx/files/1766268/ConsoleApp5.zip)

**Comment by ianhays** [comment]
@joperezr FYI:

This is still broken on the latest VS preview.

In fact, referencing net471 as a targetframework seems pretty broken all around. I tried just targeting net471 without netcoreapp and I get ```Assets file '...project.assets.json' not found. Run a NuGet package restore to generate this file.``` This is after a full clean and deletion of all bin/obj folders.

**Comment by jnm2** [comment]
I ran into this recently too.

**Comment by carlblanchard** [comment]
Yup, not working for me neither, the workaround did nothing.

**Comment by joshfree** [comment]
@weshaggard is this something you could help load balance for us?

**Comment by joperezr** [comment]
Can anyone hitting this upgrade to VS 15.6.3? We added a fix in the tooling that should fix the automatic binding redirect issue and reference the right dll which should have the method.

**Comment by commonsensesoftware** [comment]
I'm running 15.6.3 and I'm hitting a related issue. My project uses CPS with TargetFrameworks for **net452** (using full .NET refs only) and **net461** (using NuGet refs). Everything compiles, but I get MissingMethodException from `ZipFile.OpenRead` at runtime in the **net461** build. The **net452** build runs fine.

**Comment by joperezr** [comment]
`ZipFile` is a very specific case that won't be fixed by VS 15.6.3. For this very particular issue, do you mind adding a binding redirect into your net461's app.config?
```xml
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.IO.Compression.ZipFile" publicKeyToken="b77a5c561934e089" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.2.0" newVersion="4.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
```

**Comment by dejanstojanovic** [comment]
Hi, I have the same issue. I tried adding the assemblyBinding section to app.config, but it is still failing to load the proper assembly and I am getting MissingMethodException

`
Unhandled Exception: System.MissingMethodException: Method not found: 'Void Syst
em.IO.Compression.ZipFileExtensions.ExtractToFile(System.IO.Compression.ZipArchi
veEntry, System.String, Boolean)'.
`

Any other suggestion how to resolve this issues?

**Comment by joperezr** [comment]
@dejanstojanovic which version of ZipFile do you depend on? which version of the framework are you targeting (4.7.1 or 4.7.2)? which version of the framework are you running in(is installed on your machine)?

**Comment by dejanstojanovic** [comment]
Hi,
The application is targeting 4.6.1 and I am referencing the nuget System.IO.Compression.ZipFile in the packages.config
`<package id="System.IO.Compression.ZipFile" version="4.3.0" targetFramework="net461" />`
On the target machine I checked the registry for the framework version of framework and according to https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed it has framework 4.7.1 installed 
![image](https://user-images.githubusercontent.com/7481783/41081059-6b552432-6a3a-11e8-8ddc-5d1c4a9cb1ad.png)

**Comment by dejanstojanovic** [comment]
I just discovered one more weird thing. On the target machine I went to GAC C:\Windows\Microsoft.NET\assembly\GAC_MSIL\System.IO.Compression.ZipFile\v4.0_4.0.0.0__b77a5c561934e089 to check the version of System.IO.Compression.ZipFile.dll with simple PowerShell command

`([system.reflection.assembly]::loadfile("C:\Windows\Microsoft.NET\assembly\GAC_MSIL\System.IO.Compression.ZipFile\v4.0_4.0.0.0__b77a5c561934e089\System.IO.Compression.ZipFile.dll")).FullName`

The output is 
`System.IO.Compression.ZipFile, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089`

The same output I get for the assembly I referenced via nuget package and I am getting the same response, however the files are not the same. Easily noticeable by file size which is different.

So as far as I see, there are two assemblies which are obviously different but they have the same version?
I think this is the reason why config assembly resolution policy looks like not working.

**Comment by dejanstojanovic** [comment]
Finally mad it work.
I installed 4.7.1 SDK on my dev machine, set the targeting framework to 4.7.1 instead of 4.6.1, removed all packages and added references installed and re-compiled.

Finally works

**Comment by fabbrik** [comment]
The amount of time I spent with no luck trying to fix this issue is ridiculous. If u need a workaround look at this code snippet (at least will get u going):
```
using (var zip = new ZipArchive(file.InputStream))
                    {
                        foreach (ZipArchiveEntry entry in zip.Entries)
                        {
                            if (!string.IsNullOrEmpty(Path.GetExtension(entry.FullName))) //make sure it's not a folder
                            {
                                **var  deflate_stream = entry.Open();
                                using (var fileStream = System.IO.File.Create(Path.Combine(uploads, entry.FullName)))
                                {
                                    deflate_stream.CopyTo(fileStream);
                                }**
                               
                            }
                            else
                            {
                                Directory.CreateDirectory(Path.Combine(uploads, entry.FullName));
                            }
                        }
                    }
```

**Comment by tanguero** [comment]
> Finally made it work.
> I installed 4.7.1 SDK on my dev machine, set the targeting framework to 4.7.1 instead of 4.6.1, removed all packages and added references installed and re-compiled.
> 
> Finally works

will try this, thanks for sharing the wisdom

**Comment by theodoreKor** [comment]
For a similar exception  I got when trying to zip a simple file : 

Unhandled Exception: System.MissingMethodException: Method not found: 'Void System.IO.Compression.DeflateStream.

I deleted the references for System.IO.Compression and System.IO.Compression.FileSystem and added them again and it worked. 

Solution based on this link: 
https://social.msdn.microsoft.com/Forums/en-US/f8b29f09-48d8-4364-9c79-b62e38909c18/c-systemmissingmethodexception-when-trying-to-open-and-read-from-file-in-ziparchive?forum=csharpgeneral

**Comment by carlossanlop** [comment]
Judging by the last two replies by @dejanstojanovic and @theodoreKor stating that the problem has been resolved, and the fact that there are no more additional reports since July, I will close this issue.

If this is still a problem, feel free to reopen.
