### ISSUE TITLE
Update RIDs used in test execution

### ISSUE THREAD

**Issue by ianhays** [dotnet/corefx#27095]
This issue is to track updating the RIDs being used in CoreFX Jenkins testing.

Related: https://github.com/dotnet/corefx/issues/25252, https://github.com/dotnet/wcf/issues/2553, https://github.com/dotnet/core-eng/issues/2450

Current CoreFX Master Jenkins Linux RIDS:
- RHEL7.2
- CentOS7.1
- Fedora24
- Debian8.4
- Ubuntu 14.04, 16.04, 16.10

Target RIDS:
- RHEL7.4
- CentOS7.4
- Fedora27
- Debian9.0
- Ubuntu 14.04, 16.04, 18.04

Update 2/6/2018:
Remaining work:
- /+ RHEL7.4
- /+ CentOS7.4

**Comment by ianhays** [comment]
There are two ways to complete this issue:
1. Go through the new versions and add new jenkins labels for each one or attempt to use the helix queues.
2. Abandon the Jenkins testing infrastructure for innerloop/outerloop which is currently only being used for the badges and instead point our badges at some daily/onPush helix runs (which would have to be added). Depends on https://github.com/dotnet/core-eng/issues/1901. This is the far better long-term solution as it greatly reduces the cost of updating our test OS versions and also makes the badges more accurately reflect our current build&test state.

**Comment by tmds** [comment]
@ianhays great you are updating these OSes! If you want to automate the upgrade of RHEL7/CentOS7 you can do it as described here: https://linuxaria.com/howto/enabling-automatic-updates-in-centos-7-and-rhel-7.

**Comment by ianhays** [comment]
Resolved by https://github.com/dotnet/corefx/pull/27214.

We are now testing innerloop on RHEL7.4 and CentOS 7.4.

**Comment by joshfree** [comment]
The README still shows all the old distro versions

https://github.com/dotnet/corefx#build--test-status

**Comment by ianhays** [comment]
@joshfree there is a separate issue tracking the update to the badges: https://github.com/dotnet/corefx/issues/27130
