### ISSUE TITLE
Microsoft.Windows.Compatibility external function CreateSymbolicLink() throws marshal error 2

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/corefx#31769]
@Elycin commented on [Mon Aug 13 2018](https://github.com/dotnet/core/issues/1855)

# Issue Title
Microsoft.Windows.Compatability external function CreateSymbolicLink() throws marshal error 2

# General

While attempting to createa a symbolic link by invoking `kernel32` and the external bool `CreateSymbolicLink`, it always returns false and throws Marshal 2 - ERROR_FILE_NOT_FOUND.

# Environment
Operating System: Windows 10
SDK: 2.1.300
IDE: JetBrains Rider 2018.1.4

# Details
For work, I've created a simple library to handle the creation of symbolic links for each individual environment using the following Interface:
```csharp
namespace Spectero.daemon.Libraries.Symlink
{
    
    /// <summary>
    /// This interface file defines a basic layout that each environment should be implemented to.
    /// </summary>
    public interface ISymlinkEnvironment
    {
        bool Create(string symlink, string absolutePath);
        bool Delete(string symlink);
    }
}
```

For windows specifically, we have the following class that is supposed to act as a form of wrapper to create these symbolic links as needed:
```csharp
namespace Spectero.daemon.Libraries.Symlink
{
    public class Windows : ISymlinkEnvironment
    {
        /// <summary>
        /// The parent class is the class that will initialize this environment.
        /// </summary>
        private Symlink _parent;

        /// <summary>
        /// Constructor
        /// (Inherits the parent class)
        /// </summary>
        /// <param name="parent"></param>
        public Windows(Symlink parent)
        {
            _parent = parent;
        }
        
        static extern bool CreateSymbolicLink(string lpSymlinkFileName, string lpTargetFileName, Symlink.SymbolicLink dwFlags);

        /// <summary>
        /// Wrapper function to create symlink and determine the type from the absolute path.
        /// 0 = file
        /// 1 = directory
        /// </summary>
        /// <param name="symlink"></param>
        /// <param name="absolutePath"></param>
        /// <returns></returns>
        public bool Create(string symlink, string absolutePath)
        {
            return CreateSymbolicLink(symlink, absolutePath, _parent.GetAbsolutePathType(absolutePath));
        }

        /// <summary>
        /// Delete the symlink safely.
        /// </summary>
        /// <param name="linkPath"></param>
        /// <returns></returns>
        /// <exception cref="Exception"></exception>
        public bool Delete(string linkPath)
        {
            if (_parent.IsSymlink(linkPath))
            {
                switch (_parent.GetAbsolutePathType(linkPath))
                {
                    case Symlink.SymbolicLink.Directory:
                        Directory.Delete(linkPath);
                        return true;

                    case Symlink.SymbolicLink.File:
                        File.Delete(linkPath);
                        return true;

                    default:
                        return false;
                }
            }
            else
            {
                throw new Exception("Specified deletion path is not a symbolic link.");
            }
        }
    }
}
```

And lastly, the management class that initializes each environment based on what the operating system environment is:
```csharp
namespace Spectero.daemon.Libraries.Symlink
{
    public class Symlink
    {
        private ISymlinkEnvironment _environment;

        public enum SymbolicLink
        {
            File = 0,
            Directory = 1
        }

        public Symlink()
        {
            if (AppConfig.isWindows) _environment = new Windows(this);
            if (AppConfig.isUnix) _environment = new Unix(this);
        }

        public SymbolicLink GetAbsolutePathType(string absolutePath)
        {
            // Check if file.
            if (File.Exists(absolutePath))
                return SymbolicLink.File;

            // Check if directory
            if (Directory.Exists(absolutePath))
                return SymbolicLink.Directory;

            // Unsure, we should never reach this point but let's decide to use a file.
            return SymbolicLink.File;
        }

        public bool IsSymlink(string linkPath)
        {
            FileInfo pathInfo = new FileInfo(linkPath);
            return pathInfo.Attributes.HasFlag(FileAttributes.ReparsePoint);
        }

        public ISymlinkEnvironment Environment => _environment;
    }
}
```

# Potential reproduction
We've validated that the paths we provide to the second parameter is valid, and still we get Marshal 2 (ERROR_FILE_NOT_FOUND) for a directory instead of Marshal 3 (ERROR_PATH_NOT_FOUND).

We believe these steps may be able to reproduce the problem: 
1. Invoke the kernel and the external function
2. Try to create the symlink
3. Get false return code and running `Marshal.GetLastWin32Error()` returns 2.

# Other

If there's any more information I can provide, I would be glad to do so in hopes to get this issue fixed or a potential work around - I've tried reading into the mklink command but that seems to not be an option due to it not being a binary but rather a command built into the windows shell.

**Comment by danmosemsft** [comment]
@Elycin thanks for the report. I'm confused about what 's going on. Where is the implementation of CreateSymbolicLink (which binary is exporting it)? Could you please create a minimal console app repro case with all unnecessary code removed?

**Comment by Elycin** [comment]
Hi @danmosemsft,
I'm afraid i'm currently unable to get this going in a repository for you at this time, but will try to get it done when I can.

It seems I accidentally left out the `[DLLImport("kernel32")]` signature.

**Comment by karelz** [comment]
Please check your PInvoke - that is likely source of your problems: http://pinvoke.net/default.aspx/kernel32/CreateSymbolicLink.html
```c#
[DllImport("kernel32.dll")]
[return: System.Runtime.InteropServices.MarshalAs(System.Runtime.InteropServices.UnmanagedType.I1)]
static extern bool CreateSymbolicLink(string lpSymlinkFileName, string lpTargetFileName, SYMBOLIC_LINK_FLAG dwFlags);
```

If you still have a problem, please post a minimal repro that can run anywhere.

**Comment by karelz** [comment]
Great, so the marshaling problem is solved.
Now you need to debug the OS function and why it fails - it is not related to CoreFX anymore. You can try it and debug it also from C/C++.

Check out OS docs: https://docs.microsoft.com/en-us/windows/desktop/api/winbase/nf-winbase-createsymboliclinka - you may need to call GetLastError to get further information.

Closing as resolved.

**Comment by Elycin** [comment]
No, The problem is not solved. A false response means the symlink failed to be created.

**Comment by karelz** [comment]
@Elycin the .NET problem is solved.
You are now facing problem that your usage of OS API is not correct or hits some limitations of the API. You will need to troubleshoot that or follow up on some OS API forums (e.g. StackOverflow).
.NET team does not have specific knowledge about the OS API you're calling. Does it make sense?

**Comment by Elycin** [comment]
Would you be happy to take a look at the repository then? 

I've used this verbatim `extern bool` function in a .NET 4.5 app (as seen [here](https://github.com/ProjectSpectero/daemon-installers/blob/master/Windows/Windows/Program.cs#L18)) and have seen it work flawlessly, but here still fails in this dotnet core project.

Could you please elaborate on how this is a "usage of the OS API" problem, or a limitation?  
I've been up and down StackOverlfow researching this problem for a week.

The reason why I figured this issue was suitable for dotnet core is because this problem is specific to the core framework, or a tleast from what I've been able to test. I'll be happy to provide more information or testing but I'm positive this issue exists under this circumstance.

**Comment by karelz** [comment]
If you have a minimal repro (throw out everything which is not necessary, hardcode stuff) and if it works fine on .NET Framework, while it fails on .NET Core on the same machine, then we can take a look.
If it fails on both .NET Framework and .NET Core, then it is likely app usage problem of the API.

**Comment by Elycin** [comment]
I'll be sure to get on this for you within the next few hours.
