### ISSUE TITLE
StringParsingHelpers.ParseTcpGlobalStatisticsFromSnmpFile throw "System.OverflowException: Arithmetic operation resulted in an overflow."

### ISSUE THREAD

**Issue by maxd** [dotnet/corefx#34719]
In my case the [StringParsingHelpers.ParseTcpGlobalStatisticsFromSnmpFile](https://github.com/dotnet/corefx/blob/2f70dfc7382ce07bd40d38c60393a5c8e83ee53f/src/System.Net.NetworkInformation/src/System/Net/NetworkInformation/StringParsingHelpers.Statistics.cs#L329-L361) method [read data](https://github.com/dotnet/corefx/blob/2f70dfc7382ce07bd40d38c60393a5c8e83ee53f/src/System.Net.NetworkInformation/src/System/Net/NetworkInformation/LinuxTcpStatistics.cs#L15) from `/proc/net/snmp` file. It contains the following data:

```
Ip: Forwarding DefaultTTL InReceives InHdrErrors InAddrErrors ForwDatagrams InUnknownProtos InDiscards InDelivers OutRequests OutDiscards OutNoRoutes ReasmTimeout ReasmReqds ReasmOKs ReasmFails FragOKs FragFails FragCreates
Ip: 1 64 2593378738 0 4 1208227 0 0 2592170507 2577000578 28 0 0 0 0 0 0 0 0
Icmp: InMsgs InErrors InCsumErrors InDestUnreachs InTimeExcds InParmProbs InSrcQuenchs InRedirects InEchos InEchoReps InTimestamps InTimestampReps InAddrMasks InAddrMaskReps OutMsgs OutErrors OutDestUnreachs OutTimeExcds OutParmProbs OutSrcQuenchs OutRedirects OutEchos OutEchoReps OutTimestamps OutTimestampReps OutAddrMasks OutAddrMaskReps
Icmp: 56 0 0 56 0 0 0 0 0 0 0 0 0 0 58 0 58 0 0 0 0 0 0 0 0 0 0
IcmpMsg: InType3 OutType3
IcmpMsg: 56 58
Tcp: RtoAlgorithm RtoMin RtoMax MaxConn ActiveOpens PassiveOpens AttemptFails EstabResets CurrEstab InSegs OutSegs RetransSegs InErrs OutRsts InCsumErrors
Tcp: 1 200 120000 -1 5194587 6129539 1493164 371287 93 2592159585 2576867425 5349 0 1864996 0
Udp: InDatagrams NoPorts InErrors OutDatagrams RcvbufErrors SndbufErrors InCsumErrors IgnoredMulti
Udp: 10810 56 0 10871 0 0 0 0
UdpLite: InDatagrams NoPorts InErrors OutDatagrams RcvbufErrors SndbufErrors InCsumErrors IgnoredMulti
UdpLite: 0 0 0 0 0 0 0 0
```

As you can see the second `Tcp:` line contains 2592159585 (InSegs) and 2576867425 (OutSegs) values. These values out of bound of maximal values of [int](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/int) type (-2,147,483,648 to 2,147,483,647). So, it cause the following exception:

```
Unhandled Exception: System.OverflowException: Arithmetic operation resulted in an overflow.
   at System.IO.StringParser.ParseNextInt32()
   at System.Net.NetworkInformation.StringParsingHelpers.ParseTcpGlobalStatisticsFromSnmpFile(String filePath)
   at System.Net.NetworkInformation.LinuxTcpStatistics..ctor(Boolean ipv4)
   at System.Net.NetworkInformation.LinuxIPGlobalProperties.GetTcpIPv6Statistics()
   at MyExchange.Metrics.TcpMetrics..ctor(MetricsBase metrics, IReadOnlyDictionary`2 tags) in /source/Common/src/Metrics/TcpMetrics.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String shutdownMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at MyExchange.MarketData.WebSocketServer.Main(String[] args) in /source/MarketData.WS/src/Program.cs:line 14
```

Workaround: Restart server to reset accumulated statistics in `/proc/net/snmp` file but this is unacceptable workaround for everyday usage.

Additional information:

```
# dotnet --info

Host (useful for support):
  Version: 2.1.7
  Commit:  cca5d72d48

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

Let me know if required any additional information.

**Comment by rmkerr** [comment]
@wfurt is this an issue you're familiar with? I know you've made other improvements to this parsing code recently.

**Comment by wfurt** [comment]
I think this should be fixed by https://github.com/dotnet/corefx/pull/34119
It may be worth of grabbing daily build and trying it out @maxd

**Comment by maxd** [comment]
Looks like #34119 doesn't fix it. It fix the similar problem in [ParseInterfaceStatisticsTableFromFile](https://github.com/dotnet/corefx/blob/8ebea7a0bd164154805b5e3696f9f0795c5f6e4f/src/System.Net.NetworkInformation/src/System/Net/NetworkInformation/StringParsingHelpers.Statistics.cs#L405-L445) method but my problem related to [ParseTcpGlobalStatisticsFromSnmpFile](https://github.com/dotnet/corefx/blob/8ebea7a0bd164154805b5e3696f9f0795c5f6e4f/src/System.Net.NetworkInformation/src/System/Net/NetworkInformation/StringParsingHelpers.Statistics.cs#L329-L361) (compare implementation of theme methods by links).

**Comment by wfurt** [comment]
Updating to longs wold make sense - follow same pattern as the TCP change. Do you want to put up PR? If so, please do include tests as well  (you can use snapshot from your /proc file)

**Comment by maxd** [comment]
@wfurt I have prepared first version of fix [here](https://github.com/maxd/corefx/commit/727ad553638dc12be997c457c9f54055ec3a98a9). 

But before make PR I want to run tests locally. I totally don't understand how to do it. Looks like this [wiki article](https://github.com/dotnet/corefx/wiki/Build-and-run-tests#incremental-build-or-run-tests) is outdated. I have tried all ways described in `Incremental Build or Run tests` section. No one of them doesn't run tests.

Could you please explain how to run test locally for `System.Net.NetworkInformation` and `Common` projects?

**Comment by wfurt** [comment]
try this @maxd 

```
src/System.Net.NetworkInformation/tests/FunctionalTests$../../../../eng/common/msbuild.sh /t:rebuildandtest /p:outerloop=true
```

You can also do something like this to run specific test.

```export XUnitOptions="-verbose -method System.Net.NetworkInformation.Tests.IPGlobalPropertiesTest.IPGlobalProperties_TcpListeners_Succeed"```

**Comment by maxd** [comment]
Thank you a lot! It's work :)

Two questions yet:

1. I have added `System.IO.RowConfigReader#GetNextValueAsInt64` method and looks like `System.IO.RowConfigReader#GetNextValueAsInt32` method doesn't need anymore (it's using in tests only). Should I remove it?

1. I want to re-write [System.Net.NetworkInformation.StringParsingHelpers#ParseUInt64AndClampToInt64](https://github.com/dotnet/corefx/blob/203bc47a7c82968cb291679f77c8d004e2ae971d/src/System.Net.NetworkInformation/src/System/Net/NetworkInformation/StringParsingHelpers.Statistics.cs#L447-L450) method in this PR too because I suppose restriction by `long.MaxValue` doesn't solve problem. It just suppress it and this is wrong way. 

	Moreover, I don't think that somebody achieve `long.MaxValue` bound soon in this code. `long.MaxValue` is equal to 8 [exabytes](https://en.wikipedia.org/wiki/Exabyte) of data (9223372036854775807/1024^6). The Wikipedia [says](https://en.wikipedia.org/wiki/Exabyte#Usage_examples_and_size_comparisons):

	> In 2004, the global monthly Internet traffic passed 1 exabyte for the first time. ..., and as of March 2010, it was estimated at 21 exabytes per month.

	8 exabyte is very big value and I don't think that somebody can pass 40% of Internet traffic through server there this code will be work.

	So, how about just replace it to `long.Parse(pices[x], CultureInfo.InvariantCulture)`?

**Comment by wfurt** [comment]
If the code is truly not used any more I would remove it/replace it.
I don't understand the thoughts about second question.
Are you saying we  should not worry about wrapping because the range is way too big? Is there any harm with current handling? 
I think best next step is to open PR and let other to comment on. They may have different insight.

**Comment by maxd** [comment]
I have decided to leave `GetNextValueAsInt32` method because it required for `IPGlobalStatisticsTable.DefaultTtl` field (the local tests doesn't highlight this problem but CI does).

About `ParseUInt64AndClampToInt64` method. ok, I will try to create separate issue to refactor this method.

So, PR is ready (#35098). @wfurt Could you please review it?
