### ISSUE TITLE
[System.Text.Json] JsonSerializer depends on unspecified runtime behavior

### ISSUE THREAD

**Issue by filipnavara** [dotnet/corefx#36538]
The unit test "System.Text.Json.Serialization.Tests.ValueTests.ValueFail" uses the following code: 

https://github.com/dotnet/corefx/blob/master/src/System.Text.Json/tests/Serialization/Value.ReadTests.cs#L247

`Enum` is an abstract class and thus it can't be constructed. JsonSerializer tries to do it anyway here:

https://github.com/dotnet/corefx/blob/85cec01822bc70fbc45a25001997b0c1e71b1d22/src/System.Text.Json/src/JsonReflectionEmitMaterializer.cs#L13-L41

It ends up generating invalid IL (`newobj` with method referencing constructor of abstract class). This succeeds just fine on CoreCLR, but calling the resulting delegate throws `System.InvalidOperationException: Instances of abstract classes cannot be created.`.

On Mono the IL is checked earlier as part of `DynamicMethod.CreateDelegate` and throws `System.MemberAccessException: Cannot create an abstract class: System.Enum`.

I believe this should be checked explicitly in the JsonSerializer code instead of depending on the runtime accepting invalid IL code and throwing the expected exception.

/cc @bartonjs

**Comment by steveharter** [comment]
This should now be fixed because we [detect ](https://github.com/dotnet/corefx/blob/master/src/System.Text.Json/src/System/Text/Json/Serialization/JsonPropertyInfoNotNullable.cs#L20)if there is a valid public constructor.

Please re-open if not the case.

@JeremyKuhne please ensure the current Enum work fails gracefully with JsonException.

**Comment by filipnavara** [comment]
The problem is still happening. The check for `IsAbstract` is missing at https://github.com/dotnet/corefx/blob/398dc98e66b1fa59d67e7977a667b95c5e5f5135/src/System.Text.Json/src/System/Text/Json/Serialization/ReflectionEmitMemberAccessor.cs#L19
