### ISSUE TITLE
TypeDescriptor.GetAttributes() doesn't return multiples

### ISSUE THREAD

**Issue by bricelam** [dotnet/corefx#38078]
TypeDescriptor doesn't properly handle attributes with `AllowMultiple = true`.

Given a class like this...
``` csharp
[CustomValidation(typeof(Class1), nameof(Class1.Method1))]
[CustomValidation(typeof(Class1), nameof(Class1.Method2))]
class Class1
{
    public static ValidationResult Method1(object value) => null;
    public static ValidationResult Method2(object value) => null;
}
```
...only the first instance of `CustomValidationAttribute` is returned:
``` csharp
var attributes = TypeDescriptor.GetAttributes(typeof(Class1));

// Fails on .NET Core (count is 1); succeeds on .NET Framework
Debug.Assert(attributes.Count == 2);
```

This is blocking some validation scenarios in EF6.

cc @Pilchie @ajcvickers

**Comment by vcsjones** [comment]
Perhaps related to or already fixed by  #37261?

**Comment by bricelam** [comment]
Probably. I’ll try again on a build with that fix.

**Comment by bricelam** [comment]
Negative. Still failing with System.Private.CoreLib version 3.0.0-preview6.19280.1 which includes that commit.

**Comment by danmosemsft** [comment]
cc @jkotas who made that change.

**Comment by jkotas** [comment]
This problem is not related to #37261.

This is bug in the implementation of `CustomValidationAttribute`. .NET Framework has overridden `CustomValidationAttribute.TypeId` method, but .NET Core is missing this override. `System.ComponentModel` machinery is using the TypeId method to [de-duplicate the attributes](https://github.com/dotnet/corefx/blob/a10890f4ffe0fadf090c922578ba0e606ebdd16c/src/System.ComponentModel.TypeConverter/src/System/ComponentModel/ReflectTypeDescriptionProvider.ReflectedTypeData.cs#L138) and the missing override makes it think that the attribute are the same.

**Comment by jkotas** [comment]
Targeted repro:

```
using System;
using System.Linq;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

[CustomValidation(typeof(Class1), nameof(Class1.Method1))]
[CustomValidation(typeof(Class1), nameof(Class1.Method2))]
class Class1
{
    public static ValidationResult Method1(object value) => null;
    public static ValidationResult Method2(object value) => null;
}

class Program
{
    static void Main(string[] args)
    {
        var attrs = typeof(Class1).GetCustomAttributes(false);
        var attr1 = (CustomValidationAttribute)attrs[0];
        var attr2 = (CustomValidationAttribute)attrs[1];

        Console.WriteLine(attr1.Method);
        Console.WriteLine(attr2.Method);
        
        Console.WriteLine(attr1.TypeId);
        Console.WriteLine(attr2.TypeId);

        Console.WriteLine(attr1.TypeId.Equals(attr2.TypeId));
    }
}
```

Output on .NET Core:
```
Method1
Method2
System.ComponentModel.DataAnnotations.CustomValidationAttribute
System.ComponentModel.DataAnnotations.CustomValidationAttribute
True
```

Output on .NET Framework:
```
Method1
Method2
(Method1, Class1)
(Method2, Class1)
False
```

**Comment by MarcoRossignoli** [comment]
For ref https://referencesource.microsoft.com/#System.ComponentModel.DataAnnotations/DataAnnotations/CustomValidationAttribute.cs,107

**Comment by MarcoRossignoli** [comment]
Can grab is nobody is working on it.

**Comment by bricelam** [comment]
@MarcoRossignoli feel free to send a PR. I think the EF team happens to own that code... 😅
