### ISSUE TITLE
Utf8JsonReader.BytesConsumed when skipping single line comments (multi-segment) doesn't match expectations

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefx#38927]
As part of removing `BytesConsumed` from `JsonReaderState` (https://github.com/dotnet/corefx/issues/35252), I found that some of the tests were not doing what they were intending to do, mainly:
`SkipSingleLineCommentSingleSpanTest`
`ConsumeSingleLineCommentSingleSpanTest`
`SkipSingleLineCommentMultiSpanTest`
`ConsumeSingleLineCommentMultiSpanTest`

Once fixed (in https://github.com/dotnet/corefx/pull/38928), the `SkipSingleLineCommentMultiSpanTest` test started to fail because BytesConsumed is not being set properly (for all the member data - `CommentTestLineSeparators`).
The single-segment skip does the correct thing, but the multi-segment one does not. See the difference:
https://www.diffchecker.com/DYJCzkqq

https://github.com/dotnet/corefx/blob/219b67118e3a2d539afc1ff3bb2c10e1bc7b03d2/src/System.Text.Json/tests/Utf8JsonReaderTests.MultiSegment.cs#L882

```C#
[Theory]
[MemberData(nameof(CommentTestLineSeparators))]
public static void SkipSingleLineCommentMultiSpanTest(string lineSeparator)
{
    string expected = "Comment";
    string jsonData = "{//" + expected + lineSeparator + "}";
    byte[] dataUtf8 = Encoding.UTF8.GetBytes(jsonData);
    ReadOnlySequence<byte> sequence = JsonTestHelper.GetSequence(dataUtf8, 1);

    for (int i = 0; i < jsonData.Length; i++)
    {
        var state = new JsonReaderState(options: new JsonReaderOptions { CommentHandling = JsonCommentHandling.Skip });

        var json = new Utf8JsonReader(sequence.Slice(0, i), isFinalBlock: false, state);
        VerifyReadLoop(ref json, null);

        // Added some output to console to see json.BytesConsumed
        Console.WriteLine("Skip" + " : " + i + " : " + (int)state.BytesConsumed + " : " + json.BytesConsumed);

        json = new Utf8JsonReader(sequence.Slice(state.BytesConsumed), isFinalBlock: true, state);
        VerifyReadLoop(ref json, null);
    }
}
```

cc @WinCPP, @krwq

**Comment by krwq** [comment]
I think this might be already fixed in my PR: https://github.com/dotnet/corefx/pull/38036 - we got merge conflict with your latest changes so will need to rebase that

**Comment by ahsonkhan** [comment]
I tried testing on top of your change and the issue still exists.
