### ISSUE TITLE
PipeReader.ReadAsync can return empty segments

### ISSUE THREAD

**Issue by Trolldemorted** [dotnet/corefx#40892]
I just noticed that segments in a ReadResult can be empty:

![grafik](https://user-images.githubusercontent.com/10261186/64445911-ce590f80-d0d7-11e9-846d-ae255df18171.png)
I assumed that the first segment was never empty, so I often use `result.Buffer.First.Span[0];` to access the first byte.

Is this intended behaviour? Can this be caused by me writing to the pipe in a wrong way? This is how I fill my pipe from a `System.IO.Compression.DeflateStream`:

```c#
private async Task Decompress(PipeWriter writer, ReadOnlyMemory<byte> data, int count)
{
    InflateInputStream.Position = 0;
    InflateInputStream.Write(data.Span.Slice(0, count));
    InflateInputStream.Position = 0;
    InflateInputStream.SetLength(count);
    int read;

    do
    {
        Memory<byte> memory = writer.GetMemory(data.Length * 2);
        read = InflateOutputStream.Read(memory.Span);
        writer.Advance(read);
    }
    while (read != 0);
    await writer.FlushAsync();
}
```

**Comment by jkotalik** [comment]
@davidfowl @pakrym IIRC I believe this behavior can happen based on how the pipe advances internally. I remember you two had a conversation about it. Is it possible to check if the first segment is empty before returning the ReadResult?

**Comment by Trolldemorted** [comment]
Just FYI, this behaviour does not occur in my setup if I read the inflate stream's output into a dedicated buffer, and `WriteAsync` the buffer into the pipe.

**Comment by davidfowl** [comment]
Ugh yes we need to try to solve the empty segment problem. It’s a real PITA to deal with that today. Honestly I’d rather try to fix it with ReadOnlySequence itself but we’d need to measure the impact.

**Comment by jkotalik** [comment]
> but we’d need to measure the impact.

What impact would it have?

**Comment by pakrym** [comment]
ROS is very performance sensitive and we would have to add empty segment skipping code to multiple very hot paths (construction, First, enumeration etc)

**Comment by davidfowl** [comment]
I think we should at the very least try to avoid empty segments while building up the structure internally.

**Comment by pakrym** [comment]
Wonder if we should make it a rule, don't produce `ROS<>` with empty segments. We won't be able to assert it unfortunately.

**Comment by jkotalik** [comment]
I think that rule works except when the `ROS<>` is empty. 

@Trolldemorted From what I can tell, this potentially was fixed in 3.0. Could you try the latest 3.0-preview9 release and see if you hit this behavior again? https://dotnet.microsoft.com/download/dotnet-core/3.0.

**Comment by davidfowl** [comment]
@Trolldemorted can you show how you created the Pipe? In particular I want to see the PipeOptions

**Comment by Trolldemorted** [comment]
@jkotalik just making sure, you want me to upgrade to sdk preview9, but keep System.IO.Pipelines on the latest stable  release (4.5.3)? Was 34765c5 landed in the sdk? I upgraded the SDK to 3.0.100-preview9-014004 and kept System.IO.Pipelines 4.5.3 but it happened again. I also noticed other segments can be empty too:
![grafik](https://user-images.githubusercontent.com/10261186/64609649-b03c2980-d3cd-11e9-82b1-0acb247517bd.png)


@davidfowl I am using `new Pipe()` with no explicit options ([source](https://github.com/Trolldemorted/VncDotnet/blob/09a48a4012e43a6a29aa841990cd80ce3c5e9828/VncDotnet/Encodings/ZRLEEncoding.cs#L30)).

**Comment by davidfowl** [comment]
@Trolldemorted you need to update the package to preview9 of System.IO.Pipelines

**Comment by Trolldemorted** [comment]
I upgraded to 4.6.0-preview9.19421.4, but it still happens. Might be my imagination but it happens less frequently, though.

**Comment by davidfowl** [comment]
@Trolldemorted if you can provide a repro (set of steps to reproduce the empty segments) that would be great. It would mean logging what you wrote and how you called `AdvancedTo` on the other side.

**Comment by marklio** [comment]
Marking this as reliability, as First.Span[0] and FirstSpan[0] are extremely common when processing ROS.

**Comment by jkotalik** [comment]
@Trolldemorted what content is inside of test.blob?

**Comment by Trolldemorted** [comment]
I committed and pushed it, if your VS executes it in `\bin\Debug\netcoreapp3.0` the relative path should match.

It is just the beginning of an rfb stream, nothing extraordinary.

**Comment by Trolldemorted** [comment]
Do you depend on a reproducible setup that causes an empty first segment, or is my poc sufficient for now?

**Comment by GSPP** [comment]
It's a key decision whether the first segment is *guaranteed* to be not empty or not. If it's not empty in 99.999% of the cases you still can't rely on that.

It's also problematic if just a certain API (such as PipeReader) always generates non-empty first segments. Code that does `First.Span[0]` would work with such an API but fail surprisingly with others.

So I think that non-emptiness guarantee must be made (or not made) at the sequence level, not at the API level (PipeReader).

If it is decided that empty first segments can occur then it would be best if they do occur regularly in practice. If they occur only under exceptional circumstances then people will still rely on non-emptiness and write bugs that testing does not find. 

It's best if corner cases are either guaranteed not to happen, or they happen frequently enough to be exercised by testing.

**Comment by davidfowl** [comment]
I agree, while writing documentation it became evident that empty segments make the type pretty impossible to use...
