### ISSUE TITLE
[System.Text.Json] UnsafeRelaxedJsonEscaping can result in StackOverflowException

### ISSUE THREAD

**Issue by pranavkm** [dotnet/corefx#40979]
```C#
var test = new { Name = "测试11" };
Console.WriteLine(JsonSerializer.Serialize(test, new JsonSerializerOptions { Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping, PropertyNamingPolicy = JsonNamingPolicy.CamelCase }));
```

Here's what's causing the StackOverflow:

![image](https://user-images.githubusercontent.com/174281/64631901-ef0db780-d3ac-11e9-9bca-563841083e8a.png)

---------------------------------------------------
Original text:

_From @Zonciu on Tuesday, September 10, 2019 2:16:16 PM_

### Describe the bug
WebApi returning specific content cause stack overflow

#### Reproduction project
[WebApplication.zip](https://github.com/aspnet/AspNetCore/files/3596081/WebApplication.zip)

1. Using this version of NET Core 3.0 Preview 9
2. dotnet new webapi
3. Add controller methods:
```
    public class Test
    {
        public string Name { get; set; }
    }

    [ApiController]
    [Route("test")]
    public class TestController : ControllerBase
    {
        [HttpGet("1")]
        public Test Get([FromServices] ILogger<Test> logger)
        {
            logger.LogInformation("Get test 2");
            return new Test {Name = "测试"};
        }

        [HttpGet("2")]
        public Test Get2([FromServices] ILogger<Test> logger)
        {
            logger.LogInformation("Get test 2");
            return new Test {Name = "测试11"};
        }
    }
```
4. Access `/test/1` is ok, but `/test/2` causing stack overflow and crashed.

### Expected behavior
Access `/test/2`, return `{"name":"测试1"}`

### Screenshots
/test/1
![image](https://user-images.githubusercontent.com/10374056/64621218-e0101f00-d417-11e9-9fce-86ad3da7e051.png)

/test/2
![image](https://user-images.githubusercontent.com/10374056/64621165-cbcc2200-d417-11e9-9261-f6861d1708dd.png)

### Additional context
dotnet --info output
```
.NET Core SDK（反映任何 global.json）:
 Version:   3.0.100-preview9-014004
 Commit:    8e7ef240a5

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview9-014004\

Host (useful for support):
  Version: 3.0.0-preview9-19423-09
  Commit:  2be172345a

.NET Core SDKs installed:
  2.1.801 [C:\Program Files\dotnet\sdk]
  3.0.100-preview9-014004 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview9.19424.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview9-19423-09 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview9-19423-09 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

_Copied from original issue: aspnet/AspNetCore#13856_

**Comment by pranavkm** [comment]
_From @rynowak on Tuesday, September 10, 2019 2:51:25 PM_

@ahsonkhan - the only differnce between these cases appears to be the text.

**Comment by pranavkm** [comment]
_From @mkArtakMSFT on Tuesday, September 10, 2019 4:00:42 PM_

@rynowak I can repro this. yes, the only difference is the text.

**Comment by pranavkm** [comment]
_From @pranavkm on Tuesday, September 10, 2019 4:27:00 PM_

Here's the minimal repro step without MVC involved:

```C#
var test = new { Name = "测试11" };
Console.WriteLine(JsonSerializer.Serialize(test, new JsonSerializerOptions { Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping, PropertyNamingPolicy = JsonNamingPolicy.CamelCase }));
```

Here's what's causing the StackOverflow:

![image](https://user-images.githubusercontent.com/174281/64631901-ef0db780-d3ac-11e9-9bca-563841083e8a.png)

It's specifically the `UnsafeRelaxedJsonEncoding` which is what MVC uses by default for Json serialization.

**Comment by ericstj** [comment]
I suspect this is too late for 3.0, but probably for 3.0.x.  @ahsonkhan can you take a look.

**Comment by pranavkm** [comment]
@Zonciu, in the meanwhile, you could configure MVC to use the default JavaScriptEncoder which works around this particular instance of the issue:

```C#
// Startup.cs
public void ConfigureServices(IServiceCollection services)
{
    services.AddControllers().AddJsonOptions(options => options.JsonSerializerOptions.Encoder = JavaScriptEncoder.Default);
}
```

**Comment by ahsonkhan** [comment]
Fixed in master by https://github.com/dotnet/corefx/pull/40996, and in release by https://github.com/dotnet/corefx/pull/40997

**Comment by Zonciu** [comment]
@ahsonkhan @pranavkm For now I use `AddControllers().AddNewtonsoftJson()`, that works fine.

**Comment by ahsonkhan** [comment]
That works too. Let me know when you revert back to using the built-in serializer and if you find any bugs/issues or have some feedback to share.

**Comment by xcaptain** [comment]
I have the same issue using `Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping` to serialize an object causes a stack overflow, is this bug fixed? I'm using dotnet core 3 preview 9

**Comment by Zonciu** [comment]
@xcaptain It has been fixed in nightly build, but not in 3.0 rc1

**Comment by xcaptain** [comment]
I'm still having this issue even I upgraded to 3.0 rc1

![图片](https://user-images.githubusercontent.com/4054836/65232933-95bc2b80-db04-11e9-9ed0-7f3c69186e7a.png)

My code is at https://dotnetfiddle.net/5rUTaW 

if I change the `Name`  to other string it runs. @Zonciu can you help test my case?

**Comment by Zonciu** [comment]
@xcaptain 3.0 rc1 doesn't contain this fix, you need to use Newtonsoft.Json, or try the [daily build](https://github.com/dotnet/core-sdk/blob/master/README.md#installers-and-binaries)
I'd tested it in docker (nightly build 09/17/2019), it works.

**Comment by xcaptain** [comment]
@Zonciu Thanks
