### ISSUE TITLE
GenFacades failure in CI due to file in use

### ISSUE THREAD

**Issue by nguerrera** [dotnet/corefx#5236]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/windows_nt_debug_prtest/689/consoleFull#-37241274779494335-f7bd-47d0-8771-8661e00c2db2

cc @mellinoe @weshaggard 

```
11:29:16   Unhandled Exception: System.IO.IOException: The process cannot access the file 'd:\j\workspace\dotnet_corefx\windows_nt_debug_prtest\bin\obj\AnyOS.AnyCPU.Debug\System.Runtime\System.Runtime.dll' because it is being used by another process.
11:29:16      at System.IO.Win32FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs)
11:29:16      at System.IO.Win32FileSystem.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
11:29:16      at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
11:29:16      at GenFacades.Program.OutputFacadeToFile(String facadePath, HostEnvironment seedHost, Assembly facade, IAssembly contract, String pdbLocation)
11:29:16      at GenFacades.Program.Main(String[] args)
11:29:16 d:\j\workspace\dotnet_corefx\windows_nt_debug_prtest\packages\Microsoft.DotNet.BuildTools.1.0.25-prerelease-00144\lib\partialfacades.targets(101,5): error MSB3073: The command ""d:\j\workspace\dotnet_corefx\windows_nt_debug_prtest\bin/obj/AnyOS.AnyCPU.Debug\ToolRuntime\CoreRun.exe" "d:\j\workspace\dotnet_corefx\windows_nt_debug_prtest\packages/Microsoft.DotNet.BuildTools.1.0.25-prerelease-00144/lib/GenFacades.exe" -partialFacadeAssemblyPath:"d:\j\workspace\dotnet_corefx\windows_nt_debug_prtest\bin/obj/AnyOS.AnyCPU.Debug\System.Runtime\PreGenFacades\System.Runtime.dll" -contracts:"d:\j\workspace\dotnet_corefx\windows_nt_debug_prtest\bin\ref\System.Runtime\4.0.21.0\System.Runtime.dll" -seeds:"d:\j\workspace\dotnet_corefx\windows_nt_debug_prtest\packages/Microsoft.TargetingPack.Private.CoreCLR\1.0.0-rc2-23520\ref\dnxcore50\mscorlib.dll;d:\j\workspace\dotnet_corefx\windows_nt_debug_prtest\bin\Windows_NT.AnyCPU.Debug\System.Private.Uri\System.Private.Uri.dll" -facadePath:"d:\j\workspace\dotnet_corefx\windows_nt_debug_prtest\bin/obj/AnyOS.AnyCPU.Debug\System.Runtime"" exited with code -532462766. [d:\j\workspace\dotnet_corefx\windows_nt_debug_prtest\src\System.Runtime\src\System.Runtime.csproj]
```

**Comment by mellinoe** [comment]
@weshaggard I wonder if this is from multiple projects trying to build System.Runtime through a project reference? Have we hit any issues like that before?

**Comment by weshaggard** [comment]
@ericstj and I did some debugging of some similar issues today. I definitely think it is a race condition with the different ProjectReferences we likely need to figure out which library configurations are different between the different references to fix this issue.

**Comment by stephentoub** [comment]
Another case:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_windows_nt_debug/51/console
```
02:47:02   Unhandled Exception: System.IO.IOException: The process cannot access the file 'd:\j\workspace\dotnet_corefx\outerloop_windows_nt_debug\bin\obj\AnyOS.AnyCPU.Debug\System.Runtime\System.Runtime.dll' because it is being used by another process.
02:47:02      at System.IO.Win32FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs)
02:47:02      at System.IO.Win32FileSystem.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
02:47:02      at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
02:47:02      at GenFacades.Program.OutputFacadeToFile(String facadePath, HostEnvironment seedHost, Assembly facade, IAssembly contract, String pdbLocation)
02:47:02      at GenFacades.Program.Main(String[] args)
```

**Comment by ericstj** [comment]
Yeah, I fixed the pkgproj case.  The way to root cause is to examine a diag build log that builds both the .builds for the project and the one that is referencing the racing project and diff the property collection.

I can help with this if you point me at a project ref that's causing the problem.

**Comment by ericstj** [comment]
Actually it looks like my change hasn't come in from TFS yet so it's likely this is still the same bug I fixed yesterday.  https://github.com/dotnet-bot/corefx/commit/a5d558bcf7713e56c237de704f3d70c4927d8f44

**Comment by stephentoub** [comment]
I'm still seeing this, e.g.
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/windows_nt_debug_prtest/769/consoleFull
```
05:26:50   Unhandled Exception: System.IO.IOException: The process cannot access the file 'd:\j\workspace\dotnet_corefx\windows_nt_debug_prtest\bin\obj\AnyOS.AnyCPU.Debug\System.Runtime\System.Runtime.dll' because it is being used by another process.
05:26:50      at System.IO.Win32FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs)
05:26:50      System.Composition.Tests  Total: 142, Errors: 0, Failed: 0, Skipped: 0, Time: 1.199s
05:26:50      at System.IO.Win32FileSystem.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
05:26:50      at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
05:26:50      at GenFacades.Program.OutputFacadeToFile(String facadePath, HostEnvironment seedHost, Assembly facade, IAssembly contract, String pdbLocation)
05:26:50      at GenFacades.Program.Main(String[] args)
05:26:50 
d:\j\workspace\dotnet_corefx\windows_nt_debug_prtest\packages\Microsoft.DotNet.BuildTools.1.0.25-prerelease-00144\lib\partialfacades.targets(101,5): error MSB3073: The command ""d:\j\workspace\dotnet_corefx\windows_nt_debug_prtest\bin/obj/AnyOS.AnyCPU.Debug\ToolRuntime\CoreRun.exe" "d:\j\workspace\dotnet_corefx\windows_nt_debug_prtest\packages/Microsoft.DotNet.BuildTools.1.0.25-prerelease-00144/lib/GenFacades.exe" -partialFacadeAssemblyPath:"d:\j\workspace\dotnet_corefx\windows_nt_debug_prtest\bin/obj/AnyOS.AnyCPU.Debug\System.Runtime\PreGenFacades\System.Runtime.dll" -contracts:"d:\j\workspace\dotnet_corefx\windows_nt_debug_prtest\bin\ref\System.Runtime\4.0.21.0\System.Runtime.dll" -seeds:"d:\j\workspace\dotnet_corefx\windows_nt_debug_prtest\packages/Microsoft.TargetingPack.Private.CoreCLR\1.0.0-rc2-23520\ref\dnxcore50\mscorlib.dll;d:\j\workspace\dotnet_corefx\windows_nt_debug_prtest\bin\Windows_NT.AnyCPU.Debug\System.Private.Uri\System.Private.Uri.dll" -facadePath:"d:\j\workspace\dotnet_corefx\windows_nt_debug_prtest\bin/obj/AnyOS.AnyCPU.Debug\System.Runtime"" exited with code -532462766. [d:\j\workspace\dotnet_corefx\windows_nt_debug_prtest\src\System.Runtime\src\System.Runtime.csproj]
```

**Comment by stephentoub** [comment]
Again: http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/windows_nt_debug_prtest/771/consoleFull

**Comment by weshaggard** [comment]
I'm investigating this race condition.
