### ISSUE TITLE
Installing dotnet cli during the build shows Windows dialog (with files being copied)

### ISSUE THREAD

**Issue by krwq** [dotnet/corefx#5434]
As in the subject

**Comment by weshaggard** [comment]
cc @joperezr 

@krwq is there a particular issue with that? It shows the progress of unzipping. Its unfortunate that the cli is large enough to take long enough to unzip to show a dialog :(

**Comment by ellismg** [comment]
Could we not use System.IO.Compression.FileSystem to unzip instead of using the shell?

**Comment by joperezr** [comment]
@weshaggard looks like this was fixed with #5506 isn't it? @ellismg I think that if we use the shell it will show the unzip dialog which is the reason why this issue was filed.

**Comment by ellismg** [comment]
Yes.  Note on Windows 7 we will still show the dialog (see the discussion in #5544) but we'll try to use System.IO.Compression first which will not pop the dialog.
