### ISSUE TITLE
Outerloop Unix runs using stale native shims

### ISSUE THREAD

**Issue by stephentoub** [dotnet/corefx#7081]
Outerloop runs are currently failing on Unix with hundreds of failures due to System.Native.so missing some entrypoints that were added at the same time consumers of those entrypoints were added to the managed assemblies, e.g. System.IO.Pipes.dll consuming SystemNative_GetDomainSocketSizes.

**Comment by stephentoub** [comment]
https://github.com/dotnet/buildtools/pull/551

**Comment by weshaggard** [comment]
@stephentoub @Priya91 I assume this will get fixed when we update the packages? I don't like current change dotnet/buildtools#551 which always copies the latest shims as that will break other scenarios.

**Comment by stephentoub** [comment]
> I assume this will get fixed when we update the packages?

The current failure will be fixed.  The next time we update the shims with a new entrypoint, outerloop on unix will break again.

**Comment by weshaggard** [comment]
So it seems like the fix would be to update only the projects that need the live shims to have a dependency on the live shims. In other words the projects that depend on a live version of one of the IL libraries that depends on the shims.

**Comment by Priya91** [comment]
This is fixed now, and I've filed a tracking issue #7146.

**Comment by stephentoub** [comment]
This is still happening, e.g. http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_osx_debug/56/consoleFull

**Comment by Priya91** [comment]
This seems to be because of the BuildArch (x64 on native vs AnyCPU on managed). Will check what's the best way to resolve this.
