### ISSUE TITLE
System.Xml.RW.XmlSystemPathResolver.Tests failing

### ISSUE THREAD

**Issue by ramarag** [dotnet/corefx#7732]
```
   System.Xml.Tests.XmlSystemPathResolverTests.TestResolveInvalidPaths [FAIL]
      Assert.True() Failure
      Expected: True
      Actual:   False
      Stack Trace:
            at System.Xml.Tests.XmlSystemPathResolverTests.AssertInvalidPath(String path)
            at System.Xml.Tests.XmlSystemPathResolverTests.TestResolveInvalidPaths()
```

**Comment by ianhays** [comment]
I couldn't repro this on my arm64 machine:

```
Running tests... Start time: 16:00:11.87
Command(s):
call CoreRun.exe xunit.console.netcore.exe System.Xml.RW.XmlSystemPathResolver.Tests.dll  -xml testResults.xml -notrait Benchmark=true  -notrait category=OuterLoop -notrait category=failing -notrait category=nonwindowstests
xUnit.net console test runner (64-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.

Discovering: System.Xml.RW.XmlSystemPathResolver.Tests
Discovered:  System.Xml.RW.XmlSystemPathResolver.Tests
Starting:    System.Xml.RW.XmlSystemPathResolver.Tests
Finished:    System.Xml.RW.XmlSystemPathResolver.Tests

=== TEST EXECUTION SUMMARY ===
   System.Xml.RW.XmlSystemPathResolver.Tests  Total: 4, Errors: 0, Failed: 0, Skipped: 0, Time: 0.758s
```

**Comment by jiangzeng** [comment]
Re-open as this fails in AMD64 on CoreFX build 20161026.02.
Log:

Windows.10.Amd64-AnyCPU-Release 
Unhandled Exception of Type Xunit.Sdk.TrueException
Message :
Assert.True() Failure\r\nExpected: True\r\nActual:   False

Stack Trace :
   at System.Xml.Tests.XmlSystemPathResolverTests.AssertInvalidPath(String path) in D:\A\_work\31\s\corefx\src\System.Private.Xml\tests\XmlReader\XmlResolver\XmlSystemPathResolverTests.cs:line 75
   at System.Xml.Tests.XmlSystemPathResolverTests.TestResolveInvalidPaths() in D:\A\_work\31\s\corefx\src\System.Private.Xml\tests\XmlReader\XmlResolver\XmlSystemPathResolverTests.cs:line 83

Details:
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fdesktop~2Fcli~2F/build/20161026.02/workItem/System.Xml.RW.XmlSystemPathResolver.Tests/analysis/xunit/System.Xml.Tests.XmlSystemPathResolverTests~2FTestResolveInvalidPaths

**Comment by sepidehMS** [comment]
This should be fixed by https://github.com/dotnet/corefx/issues/13061

**Comment by jiangzeng** [comment]
@sepidehMS This is still happening in build 20161103.01.

Unhandled Exception of Type Xunit.Sdk.TrueException
Message :
Assert.True() Failure\r\nExpected: True\r\nActual:   False

Stack Trace :
   at System.Xml.Tests.XmlSystemPathResolverTests.AssertInvalidPath(String path) in D:\A\_work\40\s\corefx\src\System.Private.Xml\tests\XmlReader\XmlResolver\XmlSystemPathResolverTests.cs:line 76

Details:
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fdesktop~2Fcli~2F/build/20161103.01/workItem/System.Xml.RW.XmlSystemPathResolver.Tests/analysis/xunit/System.Xml.Tests.XmlSystemPathResolverTests~2FTestResolveInvalidPath

**Comment by sepidehMS** [comment]
Fixed by https://github.com/dotnet/corefx/pull/14877
