### ISSUE TITLE
ARM64: System.Net.Http.WinHttpHandler.Unit.Tests fails

### ISSUE THREAD

**Issue by ramarag** [dotnet/corefx#7736]
```
<test name="System.Net.Http.WinHttpHandlerUnitTests.WinHttpHandlerTest.SendAsync_NoWinHttpDecompressionSupportAndResponseBodyIsGZipCompressed_ExpectedResponse" type="System.Net.Http.WinHttpHandlerUnitTests.WinHttpHandlerTest" method="SendAsync_NoWinHttpDecompressionSupportAndResponseBodyIsGZipCompressed_ExpectedResponse" time="0.4168765" result="Fail">
        <failure exception-type="System.IO.Compression.ZLibException">
          <message><![CDATA[System.IO.Compression.ZLibException : The underlying compression routine could not be loaded correctly.\r\n---- System.BadImageFormatException : An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B (COR_E_BADIMAGEFORMAT))]]></message>
          <stack-trace><![CDATA[   at System.IO.Compression.Deflater.DeflateInit(CompressionLevel compressionLevel, Int32 windowBits, Int32 memLevel, CompressionStrategy strategy)
   at System.IO.Compression.Deflater..ctor(CompressionLevel compressionLevel, Int32 windowBits)
   at System.IO.Compression.DeflateStream.InitializeDeflater(Stream stream, Boolean leaveOpen, Int32 windowBits, CompressionLevel compressionLevel)
   at System.IO.Compression.DeflateStream..ctor(Stream stream, CompressionMode mode, Boolean leaveOpen, Int32 windowBits)
   at System.IO.Compression.GZipStream..ctor(Stream stream, CompressionMode mode)
   at System.Net.Http.WinHttpHandlerUnitTests.TestServer.SetResponse(DecompressionMethods compressionKind, String responseBody)
   at System.Net.Http.WinHttpHandlerUnitTests.WinHttpHandlerTest.<>c__DisplayClass55_0.<SendAsync_NoWinHttpDecompressionSupportAndResponseBodyIsGZipCompressed_ExpectedResponse>b__0()
   at System.Net.Http.WinHttpHandlerUnitTests.SendRequestHelper.Send(WinHttpHandler handler, Action setup, String fakeServerEndpoint)
   at System.Net.Http.WinHttpHandlerUnitTests.SendRequestHelper.Send(WinHttpHandler handler, Action setup)
   at System.Net.Http.WinHttpHandlerUnitTests.WinHttpHandlerTest.<SendAsync_NoWinHttpDecompressionSupportAndResponseBodyIsGZipCompressed_ExpectedResponse>d__55.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
----- Inner Stack Trace -----
   at Interop.zlib.deflateInit2_(Byte* stream, Int32 level, Int32 method, Int32 windowBits, Int32 memLevel, Int32 strategy, Byte* version, Int32 stream_size)
   at Interop.zlib.DeflateInit2_(ZStream& stream, CompressionLevel level, CompressionMethod method, Int32 windowBits, Int32 memLevel, CompressionStrategy strategy)
   at System.IO.Compression.ZLibNative.ZLibStreamHandle.DeflateInit2_(CompressionLevel level, Int32 windowBits, Int32 memLevel, CompressionStrategy strategy)
   at System.IO.Compression.Deflater.DeflateInit(CompressionLevel compressionLevel, Int32 windowBits, Int32 memLevel, CompressionStrategy strategy)]]></stack-trace>
        </failure>
      </test>
      <test name="System.Net.Http.WinHttpHandlerUnitTests.WinHttpHandlerTest.SendAsync_NoWinHttpDecompressionSupportAndResponseBodyIsDeflateCompressed_ExpectedResponse" type="System.Net.Http.WinHttpHandlerUnitTests.WinHttpHandlerTest" method="SendAsync_NoWinHttpDecompressionSupportAndResponseBodyIsDeflateCompressed_ExpectedResponse" time="0.2029853" result="Fail">
        <failure exception-type="System.IO.Compression.ZLibException">
          <message><![CDATA[System.IO.Compression.ZLibException : The underlying compression routine could not be loaded correctly.\r\n---- System.BadImageFormatException : An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B (COR_E_BADIMAGEFORMAT))]]></message>
          <stack-trace><![CDATA[   at System.IO.Compression.Deflater.DeflateInit(CompressionLevel compressionLevel, Int32 windowBits, Int32 memLevel, CompressionStrategy strategy)
   at System.IO.Compression.Deflater..ctor(CompressionLevel compressionLevel, Int32 windowBits)
   at System.IO.Compression.DeflateStream.InitializeDeflater(Stream stream, Boolean leaveOpen, Int32 windowBits, CompressionLevel compressionLevel)
   at System.IO.Compression.DeflateStream..ctor(Stream stream, CompressionMode mode, Boolean leaveOpen, Int32 windowBits)
   at System.IO.Compression.DeflateStream..ctor(Stream stream, CompressionMode mode)
   at System.Net.Http.WinHttpHandlerUnitTests.TestServer.SetResponse(DecompressionMethods compressionKind, String responseBody)
   at System.Net.Http.WinHttpHandlerUnitTests.WinHttpHandlerTest.<>c__DisplayClass54_0.<SendAsync_NoWinHttpDecompressionSupportAndResponseBodyIsDeflateCompressed_ExpectedResponse>b__0()
   at System.Net.Http.WinHttpHandlerUnitTests.SendRequestHelper.Send(WinHttpHandler handler, Action setup, String fakeServerEndpoint)
   at System.Net.Http.WinHttpHandlerUnitTests.SendRequestHelper.Send(WinHttpHandler handler, Action setup)
   at System.Net.Http.WinHttpHandlerUnitTests.WinHttpHandlerTest.<SendAsync_NoWinHttpDecompressionSupportAndResponseBodyIsDeflateCompressed_ExpectedResponse>d__54.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
----- Inner Stack Trace -----
   at Interop.zlib.deflateInit2_(Byte* stream, Int32 level, Int32 method, Int32 windowBits, Int32 memLevel, Int32 strategy, Byte* version, Int32 stream_size)
   at Interop.zlib.DeflateInit2_(ZStream& stream, CompressionLevel level, CompressionMethod method, Int32 windowBits, Int32 memLevel, CompressionStrategy strategy)
   at System.IO.Compression.ZLibNative.ZLibStreamHandle.DeflateInit2_(CompressionLevel level, Int32 windowBits, Int32 memLevel, CompressionStrategy strategy)
   at System.IO.Compression.Deflater.DeflateInit(CompressionLevel compressionLevel, Int32 windowBits, Int32 memLevel, CompressionStrategy strategy)]]></stack-trace>
        </failure>
      </test>
```

**Comment by davidsh** [comment]
I think the issues with clrcompression dll have been resolved separately.  Closing this for now

**Comment by kyulee1** [comment]
This is still failing since we haven't enabled arm64 native components yet for corefx.

**Comment by davidsh** [comment]
>This is still failing since we haven't enabled arm64 native components yet for corefx.

@kyulee1 @stephentoub 

So, who should this issue be assigned to?  The root problem is not System.Net components but rather some native component / infrastructure.

**Comment by kyulee1** [comment]
Yes. I'm going to leave assignees for now. But we need to leave this open to track where we are at until we have full test automation in place.

**Comment by davidsh** [comment]
Ok. I will assign to @josh for now since this is a global issue across many components.

**Comment by davidsh** [comment]
@ianhays Are you actively working on this ARM64 stuff?  If not, we'll change it to un-assigned.  Thx.

**Comment by ViktorHofer** [comment]
@kyulee1 is this still an issue? And if yes, please describe it in more detail.

**Comment by carlossanlop** [comment]
Closing since there have not been any more reports of this in the last 2 years.
