### ISSUE TITLE
Windows Nano runs are not working on Jenkins

### ISSUE THREAD

**Issue by Priya91** [dotnet/corefx#9975]
Recently (after Jul 7 buildtools update) on build.cmd /p:OSGroup=Windows_NT is dropping assemblies that build for AnyOS to both tests/AnyOS.AnyCPU.Configuration/lib/netcoreapp1.0 and tests/Windows_NT.AnyCPU.Configuration/lib/netcoreapp1.0. These libs mostly have the builds file authored for AnyOS on netcoreapp1.0 and Windows_NT for net46 and netcore50, for ex, [System.AppContext.Tests.builds](https://github.com/dotnet/corefx/blob/master/src/System.AppContext/tests/System.AppContext.Tests.builds).

This change is causing Windows Nano builds to fail, as there is no RunTests.cmd generated for the net46 and netcore50 sku in tests\Windows_NT.AnyCPU.Configuration\lib\netcoreapp1.0. The test TFM folder name is also wrong (netcoreapp1.0) for the net46 and netcore50 sku.

cc @karajas

**Comment by MattGal** [comment]
Adding @karajas.

TestTFM values are configured to default to netcoreapp1.0, so that's expected.  Any time a test builds for a given TFM, the runner script will get generated.  I don't think Desktop .NET 4.6 or UWP would be supported at all on Core, so that may be why their scripts don't get generated.  Karthik can comment further.

**Comment by stephentoub** [comment]
cc: @karelz, @weshaggard, @Petermarcu 
Due to this issue, we've not been testing anything in CI on Nano Server for months.
If we care about Nano Server (which I assume we do), we should fix this asap.
If we don't care about it, we should remove the legs from CI and remove the badges from the home page.

**Comment by Priya91** [comment]
> Due to (I assume) this issue, we've not been testing anything in CI on Nano Server for months.

The build system has diverged a lot in the past few months, and the nano scripts haven't been updated to reflect those changes in buildtools and corefx. At a quick glance, the run-test.cmd is still testing the stuff under netcoreapp1.0, but the test folder structure has changed in master to ```$(TargetGroup).netcoreapp1.1\netcoreapp1.1```. As a result no tests are being run. The Nano Server scripts require an update according to the current test structure in corefx.

**Comment by karelz** [comment]
@Petermarcu what is our priority for Nano investments now?

cc: @danmosemsft

**Comment by weshaggard** [comment]
When we do fix this we should avoid duplicating this information in this special runtest.cmd file and instead call the individual test runtests.cmd files. We don't need yet another place that needs to be updated when we make test infra changes they should be consistent.

**Comment by Priya91** [comment]
> When we do fix this we should avoid duplicating this information in this special runtest.cmd file and instead call the individual test runtests.cmd files

The current run-test.cmd does that, it executes the individual runtest.cmds

**Comment by weshaggard** [comment]
We should still try to figure out a way to avoid the duplicated information. In this case "netcoreapp1.0".

**Comment by danmosemsft** [comment]
@smile21prc can you update this issue with what remains here. are you still shooting to have nano work in Jenkins for 2.0?

**Comment by danmosemsft** [comment]
@mmitche is finishing off making this work.

**Comment by weshaggard** [comment]
@mmitche is this something you are targeting for 2.0? 

Also I assume we will no longer be relying on run-test.cmd and can delete it as part of this work.

**Comment by mmitche** [comment]
@weshaggard Yes

**Comment by stephentoub** [comment]
@mmitche, when do we expect this to be up and running?

**Comment by mmitche** [comment]
@stephentoub The .Open nano Helix queue should be available this week, and then my pipeline PR will be merged and it will be available.

**Comment by stephentoub** [comment]
Thanks, @mmitche.

**Comment by weshaggard** [comment]
@mmitche what is the next steps for getting the Nano CI turned on?

**Comment by mmitche** [comment]
It's available right now.  You may request with '@dotnet-bot test portable windows debug pipeline' and '@dotnet-bot test portable windows release pipeline'.

When the runs are totally clean, we can turn this on be default in CI.  I'd like to merge #20107 first to improve some of the GitHub reporting.

**Comment by danmosemsft** [comment]
@saurabh500 fyi how to trigger Nano on a PR.

**Comment by danmosemsft** [comment]
> When the runs are totally clean, we can turn this on be default in CI

What issues remain? The Outerloop has no nano specific issues I'm aware of, so inner loop should be fine.

**Comment by weshaggard** [comment]
Addressed with https://github.com/dotnet/corefx/pull/20250.

**Comment by karelz** [comment]
Reopening to track port to 2.0 (the bug has milestone 2.0, but the PR #20250 went into master (2.1))

**Comment by danmosemsft** [comment]
As far as I know we aren't porting @mmitche 's pipeline stuff to 2.0. We still get Nano coverage in Helix in 2.0.

**Comment by weshaggard** [comment]
I would actually like to see the CI changes ported to 2.0.0 because we want to eliminate the non-portable CI legs in the 2.0.0 release build as well.

**Comment by danmosemsft** [comment]
@mmitche is this done? if not do you plan to? it's in the 2.0 milestone.

**Comment by weshaggard** [comment]
This is done now that we have Nano testing happening from the portable windows builds leg.
